import {foundationEnabled,query} from '../../lib/foundation/db';
import {requireRole} from '../../lib/foundation/session';
import {setBusinessStatus,registerPayment,report,logout} from '../../lib/foundation/actions';
import {ActionForm} from '../../lib/foundation/forms';
import {Field,Hidden} from '../../lib/foundation/fields';
import {redirect} from 'next/navigation';
export const dynamic='force-dynamic';
const states=['registrado','cotizando','pago_pendiente','activo','por_vencer','pausado','cancelado'];
export default async function Admin({searchParams}:{searchParams:Promise<{business?:string}>}){
 if(!foundationEnabled())redirect('/demo/admin');
 const actor=await requireRole('superadmin');const params=await searchParams;
 const businesses=await query(actor,'select id,name,slug,status,paid_until from nival_pr.businesses order by created_at desc limit 100');
 const b=businesses.find(b=>b.id===params.business)||businesses[0];
 const audit=b?await query(actor,'select action,data,created_at from nival_pr.audit_log where business_id=$1 order by created_at desc limit 20',[b.id]):[];
 const payments=b?await query(actor,'select amount,method,paid_at,period_start,period_end from nival_pr.payments where business_id=$1 order by paid_at desc limit 20',[b.id]):[];
 return <main className="dashboard"><header className="dashHead"><div><small>NIVAL · ADMINISTRACIÓN</small><h1>Operación Nival</h1><p>Pagos manuales y seguimiento de Google.</p></div><form action={logout}><button>Cerrar sesión</button></form></header><section className="reviewBox"><h2>Negocios</h2>{businesses.map(b=><p key={b.id}><a href={'/admin?business='+b.id}>{b.name}</a> · {b.status}</p>)}{!businesses.length&&<p>Todavía no hay negocios registrados.</p>}</section>{b&&<><section className="reviewBox"><h2>{b.name}</h2><ActionForm action={setBusinessStatus} label="Actualizar estado"><Hidden name="businessId" value={b.id}/><label>Estado<select name="status" defaultValue={b.status}>{states.map(s=><option key={s}>{s}</option>)}</select></label></ActionForm><p>Activar el estado requiere también una vigencia vigente para registrar visitas.</p></section><section className="reviewBox"><h2>Registrar pago</h2><ActionForm action={registerPayment}><Hidden name="businessId" value={b.id}/><Field name="amount" label="Importe MXN" type="number" min={1} value={399}/><label>Método<select name="method"><option value="transferencia">Transferencia</option><option value="efectivo">Efectivo</option><option value="mercado_pago">Mercado Pago</option><option value="otro">Otro</option></select></label><Field name="reference" label="Referencia" required={false}/><Field name="start" label="Inicio del período" type="date"/><Field name="end" label="Fin del período (incluido)" type="date"/></ActionForm>{payments.map((p,i)=><p key={i}>${p.amount} · {p.method} · {String(p.period_start).slice(0,10)} a {String(p.period_end).slice(0,10)}</p>)}</section><section className="reviewBox"><h2>Cargar reporte mensual</h2><ActionForm action={report}><Hidden name="businessId" value={b.id}/><Field name="period" label="Mes" type="month"/><label>Calificación de la ficha<input name="rating" type="number" min="1" max="5" step="0.1" required/></label><Field name="total" label="Reseñas totales" type="number" min={0}/><Field name="new" label="Reseñas nuevas del mes" type="number" min={0}/><Field name="answered" label="Respuestas registradas" type="number" min={0}/><label className="wide">Notas y recomendaciones<textarea name="notes" maxLength={5000}/></label></ActionForm></section><section className="reviewBox"><h2>Auditoría del negocio</h2>{audit.map((a,i)=><p key={i}>{new Date(a.created_at).toLocaleString('es-MX',{timeZone:'America/Mexico_City'})} · {a.action}: {a.data.old} → {a.data.new}</p>)}</section></>}</main>;
}
