'use client';
import {useEffect,useState} from 'react';
import {useLocalData} from '../../lib/use-local-data';
import {reviewsValid} from '../../lib/validators';
import {reviewMetrics,type Review} from '../../lib/metrics';
import DemoNotice from '../components/demo-notice';
const empty:Review[]=[];
export default function Reviews(){
 const reviews=useLocalData('nival-reviews-v1',empty,reviewsValid);
 const [author,setAuthor]=useState('');const[rating,setRating]=useState(5);const[text,setText]=useState('');const[date,setDate]=useState('');const[month,setMonth]=useState('');const[notice,setNotice]=useState('');const[onlyPending,setOnlyPending]=useState(true);
 useEffect(()=>{const today=new Date().toISOString().slice(0,10);setDate(today);setMonth(today.slice(0,7));},[]);
 function add(e:React.FormEvent){e.preventDefault();if(reviews.error)return;if(date>new Date().toISOString().slice(0,10)){setNotice('La fecha no puede estar en el futuro.');return;}if(reviews.data.some(r=>r.author===author.trim()&&r.date===date&&r.text===text.trim())){setNotice('Esta reseña ya está registrada.');return;}if(reviews.save([...reviews.data,{id:crypto.randomUUID(),author:author.trim(),rating,text:text.trim(),date,answeredAt:null}])){setAuthor('');setText('');setNotice('Reseña registrada.');}}
 const stats=reviewMetrics(reviews.data,month);
 const visible=reviews.data.filter(r=>r.date.slice(0,7)===month&&(!onlyPending||!r.answeredAt)).sort((a,b)=>b.date.localeCompare(a.date));
 return <main className="dashboard"><DemoNotice/><header className="dashHead"><div><small>NIVAL · SEGUIMIENTO MANUAL</small><h1>Reseñas de Google</h1><p>Captura lo que revisaste en Google y confirma las respuestas que publicaste.</p></div><a href="/negocio">Ver resumen</a></header><label className="filter">Mes<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><section className="stats"><article><span>Nuevas</span><b>{stats.total}</b></article><article><span>Positivas · 4 y 5 estrellas</span><b>{stats.positive}</b></article><article><span>Neutrales · 3 estrellas</span><b>{stats.neutral}</b></article><article><span>Negativas · 1 y 2 estrellas</span><b>{stats.negative}</b></article><article><span>Respondidas</span><b>{stats.answered}</b></article><article><span>Por responder</span><b>{stats.total-stats.answered}</b></article></section>
 <p role="status">{notice}</p>{reviews.error&&<p role="alert" className="error">{reviews.error}</p>}
 <section className="reviewBox"><h2>Registrar reseña</h2><form className="configGrid" onSubmit={add}><label>Nombre en Google<input required maxLength={100} value={author} onChange={e=>setAuthor(e.target.value)}/></label><label>Calificación<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} estrellas</option>)}</select></label><label>Fecha de la reseña<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="wide">Texto (opcional)<textarea maxLength={5000} value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={!reviews.ready||!!reviews.error||!author.trim()}>Guardar reseña</button></form></section>
 <section className="businesses"><h2>Bandeja de reseñas</h2><label><input type="checkbox" checked={onlyPending} onChange={e=>setOnlyPending(e.target.checked)}/> Solo pendientes</label>{visible.length===0&&<p className="empty">No hay reseñas {onlyPending?'pendientes ':''}en este mes.</p>}{visible.map(r=>{const overdue=r.rating<=2&&!r.answeredAt&&Date.now()-Date.parse(r.date+'T23:59:59')>48*3600000;return <article key={r.id} className={overdue?'overdue':''}><div><h3>{r.author} · {r.rating}/5</h3><p>{r.date}{overdue?' · Negativa pendiente por más de 48 h':''}</p><p>{r.text||'Sin texto'}</p>{r.answeredAt&&<p>Respuesta confirmada: {new Date(r.answeredAt).toLocaleDateString('es-MX')}</p>}</div><button disabled={!!reviews.error} onClick={()=>{if(!r.answeredAt&&!window.confirm('¿Ya publicaste la respuesta en Google?'))return;if(reviews.save(reviews.data.map(x=>x.id===r.id?{...x,answeredAt:r.answeredAt?null:new Date().toISOString()}:x)))setNotice(r.answeredAt?'Marcada pendiente.':'Respuesta confirmada.');}}>{r.answeredAt?'Volver a pendiente':'Confirmar respuesta publicada'}</button></article>})}</section></main>;
}
