Object.assign(process.env,{SESSION_SECRET:require('node:crypto').randomBytes(32).toString('hex')});
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
function load(file,dependencies){const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const m={exports:{}};new Function('require','exports','module',output)(name=>{if(!(name in dependencies))throw Error('Missing mock: '+name);return dependencies[name];},m.exports,m);return m.exports;}
async function access(user,profileRole='superadmin'){const policy=await import('../lib/security/admin-policy.mjs');const writes=[];const jar={delete:name=>writes.push(['delete',name]),set:(...args)=>writes.push(['cookie',...args])};const module=load('lib/security/admin-access.ts',{'server-only':{},'next/headers':{cookies:async()=>jar,headers:async()=>new Headers()},'node:crypto':require('node:crypto'),'../backend/auth':{getAuth:()=>({getSession:async()=>({data:{user,session:{id:'session-id'}}})})},'../foundation/db':{authScope:()=>({role:'auth'}),query:async(_,sql,...args)=>{writes.push(['query',sql,...args]);return sql.includes('select id,role')?[{id:'provider-id',role:profileRole}]:[{accepted:true}];}},'../foundation/session':{secret:()=> 'x'.repeat(32),staffCookie:'staff',routeCookie:'route',adminCookie:'admin',cookieOptions:{}},'../foundation/security.mjs':{signedHint:()=> 'signed-admin-hint'},'../points/security':{assertSameOrigin:async()=>{}},'./admin-policy.mjs':policy,'./admin-proof.mjs':{signAdminProof:()=> 'proof'},'./client-ip':{trustedClientIp:()=> 'test-client'}});return {module,writes};}
test('private authorization never grants an unverified or different identity',async()=>{for(const user of [null,{id:'u',email:'other@example.com',emailVerified:true},{id:'u',email:'rodrigoarchundia379@gmail.com',emailVerified:false}]){const {module,writes}=await access(user);assert.equal(await module.authorizeOwnAdministrator(),false);assert.deepEqual(writes,[]);}});
test('private authorization binds permission to the verified provider user and refreshes route cookies',async()=>{const {module,writes}=await access({id:'provider-id',email:'rodrigoarchundia379@gmail.com',emailVerified:true,name:'Rodrigo'});assert.equal(await module.authorizeOwnAdministrator(),true);assert.match(writes[0][1],/select id,role from nival_pr.profiles/);assert.deepEqual(writes[0][2],['provider-id']);assert.deepEqual(writes[1],['delete','staff']);assert.equal(writes[2][1],'route');assert.equal(writes[3][1],'admin');});
test('private authorization does not create admin privileges for an owner profile',async()=>{const {module,writes}=await access({id:'provider-id',email:'rodrigoarchundia379@gmail.com',emailVerified:true},'owner');assert.equal(await module.authorizeOwnAdministrator(),false);assert.equal(writes.length,1);assert.match(writes[0][1],/select id,role/);});
test('the private endpoint rejects other emails before account creation or permission writes',async()=>{const {module,writes}=await access(null);await assert.rejects(module.limitAdminAccess('other@example.com'),/reservado/);assert.deepEqual(writes,[]);});
test('every authenticated admin profile is checked against the verified allowed identity',async()=>{const policy=await import('../lib/security/admin-policy.mjs');for(const email of ['rodrigoarchundia379@gmail.com','other@example.com']){const mod=load('lib/foundation/session.ts',{'server-only':{},'next/headers':{cookies:async()=>({get:()=>({value:'proof'})})},'next/navigation':{},'../backend/auth':{getAuth:()=>({getSession:async()=>({data:{user:{id:'u',email,emailVerified:true,name:'Rodrigo'},session:{id:'session-id'}}})})},'./db':{authScope:()=>({}),query:async(_,sql)=>sql.includes('ensure_owner')?[]:[{id:'u',role:'superadmin',full_name:'Rodrigo'}]},'./security.mjs':{},'../security/admin-policy.mjs':policy,'../security/admin-proof.mjs':{validAdminProof:()=>true}});const actor=await mod.emailActor();assert.equal(actor?.role||null,email.startsWith('rodrigoarchundia')?'superadmin':null);}});
test('public login and signup reject the reserved administrator email before reaching the provider',async()=>{
 const policy=await import('../lib/security/admin-policy.mjs');let called=false;
 const route=load('app/api/auth/[...path]/route.ts',{'next/headers':{},'node:crypto':require('node:crypto'),'../../../../lib/backend/auth':{getAuth:()=>{called=true;throw Error('Unexpected provider call');}},'../../../../lib/foundation/db':{},'../../../../lib/foundation/session':{},'../../../../lib/security/turnstile-cookie.mjs':{},'../../../../lib/points/security':{assertSameOrigin:async()=>{}},'../../../../lib/security/client-ip':{},'../../../../lib/security/admin-policy.mjs':policy});
 for(const path of ['sign-in/email','sign-up/email']){const response=await route.POST(new Request('https://nival.example/api/auth/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'rodrigoarchundia379@gmail.com',password:'attacker-chosen'})}),{});assert.equal(response.status,403);}
 assert.equal(called,false);
});
test('first access creates an unknowable password, revokes auto-signup session and sends only founder mailbox links',async()=>{
 const calls=[];const auth={signUp:{email:async values=>{calls.push(['signup',values]);return {}; }},signOut:async()=>{calls.push(['signout']);return {};},sendVerificationEmail:async v=>{calls.push(['verify',v]);return {};},requestPasswordReset:async v=>{calls.push(['reset',v]);return {};}};
 const mod=load('app/acceso-administrador/actions.ts',{'../../lib/backend/auth':{getAuth:()=>auth},'node:crypto':require('node:crypto'),'../../lib/foundation/db':{systemQuery:async()=>[]},'../../lib/security/admin-access':{limitAdminAccess:async()=> 'https://nival.example',limitAdminEmailRequest:async()=>{},authorizeOwnAdministrator:async()=>{throw Error('No grants during setup');}}});
 const form=new FormData();form.set('email','rodrigoarchundia379@gmail.com');form.set('password','attacker-chosen');
 const result=await mod.administratorAccess('setup',form);assert.equal(result.ok,true);assert.equal(result.enter,undefined);assert.notEqual(calls[0][1].password,'attacker-chosen');assert.equal(calls[0][1].password.length,64);assert.equal(calls[1][0],'signout');assert.equal(calls[2][1].email,'rodrigoarchundia379@gmail.com');assert.equal(calls[3][1].redirectTo,'https://nival.example/acceso-administrador/restablecer');
});
