import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
const a='11111111-1111-4111-8111-111111111111';const b='22222222-2222-4222-8222-222222222222';const operator='33333333-3333-4333-8333-333333333333';
async function setup(){const db=new PGlite();await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth,public to authenticated,anon; grant execute on function auth.uid() to authenticated; insert into auth.users values('${a}'),('${b}'),('${operator}');`);await db.exec(readFileSync('database/bootstrap.sql','utf8'));await db.exec(readFileSync('database/diagnostics.sql','utf8'));return db;}
async function as(db,id){await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false);`);}
async function business(db,id,name){await as(db,id);return(await db.query('insert into public.npr_businesses(owner_id,name) values($1,$2) returning id',[id,name])).rows[0].id;}
test('owners only see their data and cannot promote themselves to operator',async()=>{const db=await setup();try{const ba=await business(db,a,'Negocio A');await business(db,b,'Negocio B');await as(db,a);assert.equal((await db.query('select name from npr_businesses')).rows.length,1);await assert.rejects(db.query('insert into npr_operators(user_id) values($1)',[a]),/permission denied/);await assert.rejects(db.query('update npr_businesses set owner_id=$1 where id=$2',[b,ba]),/permission denied/);await as(db,b);await assert.rejects(db.query('insert into npr_customers(business_id,name) values($1,$2)',[ba,'Ajeno']),/row-level security/);await db.exec('reset role; set role anon;');await assert.rejects(db.query('select * from npr_businesses'),/permission denied/);}finally{await db.close();}});
test('visits award one point; reward cannot overdraw or use arbitrary amount',async()=>{const db=await setup();try{const bid=await business(db,a,'A');const cid=(await db.query("insert into npr_customers(business_id,name) values($1,'Cliente') returning id",[bid])).rows[0].id;const add=(kind,points)=>db.query('insert into npr_movements(business_id,customer_id,kind,points) values($1,$2,$3,$4)',[bid,cid,kind,points]);await assert.rejects(add('redeem',-5),/Insufficient points/);await assert.rejects(add('visit',100),/check constraint/);for(let i=0;i<5;i++)await add('visit',1);await assert.rejects(add('redeem',-1),/Invalid reward amount/);await add('redeem',-5);assert.equal(Number((await db.query('select sum(points) as balance from npr_movements')).rows[0].balance),0);await assert.rejects(add('redeem',-5),/Insufficient points/);await assert.rejects(db.query('delete from npr_movements'),/permission denied/);}finally{await db.close();}});
test('only operator writes reviews, owners can read theirs',async()=>{const db=await setup();try{const bid=await business(db,a,'A');await assert.rejects(db.query("insert into npr_reviews(business_id,author,rating,review_date) values($1,'Autor',5,'2026-10-01')",[bid]),/row-level security/);await db.exec('reset role');await db.query('insert into npr_operators values($1)',[operator]);await as(db,operator);await db.query("insert into npr_reviews(business_id,author,rating,review_date) values($1,'Autor',3,'2026-10-01')",[bid]);await as(db,a);assert.equal((await db.query('select * from npr_reviews')).rows.length,1);await as(db,b);assert.equal((await db.query('select * from npr_reviews')).rows.length,0);}finally{await db.close();}});

test('diagnostics are operator-only writes and owners only read their own history',async()=>{const db=await setup();try{const bid=await business(db,a,'A');await business(db,b,'B');const insert=()=>db.query("insert into npr_diagnostics(business_id,checked_on,rating,review_count,findings,recommendations) values($1,'2026-10-01',4.3,12,'Fotos desactualizadas','Actualizar fotos')",[bid]);await as(db,a);await assert.rejects(insert(),/row-level security/);await db.exec('reset role');await db.query('insert into npr_operators values($1)',[operator]);await as(db,operator);await insert();await assert.rejects(insert(),/unique constraint/);await as(db,a);assert.equal((await db.query('select * from npr_diagnostics')).rows.length,1);await assert.rejects(db.query("update npr_diagnostics set rating=5"),/permission denied/);await as(db,b);assert.equal((await db.query('select * from npr_diagnostics')).rows.length,0);await db.exec('reset role; set role anon;');await assert.rejects(db.query('select * from npr_diagnostics'),/permission denied/);}finally{await db.close();}});
