import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
const owner='11111111-1111-4111-8111-111111111111',admin='22222222-2222-4222-8222-222222222222';
const source=p=>readFileSync(p,'utf8');
const sql=(path,start,end)=>{const s=source(path),i=s.indexOf(start);assert.ok(i>=0,start);return s.slice(i,s.indexOf(end,i));};
test('first sale: registration → paid code → setup → enrollment → owner visit → staff redemption → recovery → expiry',async()=>{
 const db=new PGlite();
 try{
  await db.exec('create schema neon_auth;create table neon_auth."user"(id uuid primary key)');
  for(const name of ['foundation-neon','points-neon','points-lifecycle','points-legacy-phones','owner-panel','owner-report-scope','legal-pilot','registration-pilot','reputation-v6','lealtad-v6','points-only-plan-v1','activation-plan-v2','entitlements-v2','owner-tools-v2','service-access-v3'])await db.exec(source('database/'+name+'.sql'));
  await db.query('insert into neon_auth."user" values($1),($2)',[owner,admin]);
  await db.query("insert into nival_pr.profiles(id,role,full_name) values($1,'owner','Ana'),($2,'superadmin','Nival')",[owner,admin]);
  const scope=async(role,id='')=>{await db.exec('reset role;set role '+role);await db.query("select set_config('npr.user_id',$1,false)",[id]);};
  await scope('npr_v2_auth',owner);
  const {rows:[registered]}=await db.query('select nival_pr_private.register_business_plan_complete($1,$2,$3,$4,$5,$6,$7,true,$8,299) id',['primer-cliente','Café Ana','Cafetería / restaurante','Ana','525512345678','ana@example.com','https://maps.app.goo.gl/example','piloto-borrador-2026-10-05']);const b=registered.id;
  const publicData=async()=> (await db.query('select nival_pr_private.public_business($1) data',['primer-cliente'])).rows[0].data;
  assert.equal((await publicData()).active,false);
  await scope('npr_v2_admin',admin);
  await db.query(sql('lib/admin/actions.ts','with locked as (select * from nival_pr.businesses','`,values:'),[b,299,'efectivo','Pago primera venta',admin]);
  assert.equal((await db.query('select status from nival_pr.businesses where id=$1',[b])).rows[0].status,'pago_pendiente');
  await db.query(sql('lib/admin/actions.ts','insert into nival_pr.activation_codes(code,','`,[businessId,code'),[b,'NIV-ABCD-1234',72,admin]);
  await db.exec('reset role');
  const activation=sql('lib/admin/actions.ts','with claimed as (','`,[code,businessId]');
  assert.equal((await db.query(activation,['NIV-ABCD-1234',b])).rows.length,1);
  assert.equal((await db.query(activation,['NIV-ABCD-1234',b])).rows.length,0,'Single use');
  await scope('npr_v2_owner',owner);
  await db.query(sql('lib/foundation/actions.ts','insert into nival_pr.programs(business_id,name,mode,','",\n      ['),[b,'Café Ana · recompensas','single',2,'#164d3b',JSON.stringify({min_hours_between_visits:4,max_visits_per_day:1}),null]);
  const {rows:[reward]}=await db.query(sql('lib/foundation/actions.ts','insert into nival_pr.rewards(program_id,name,points_cost,position)','",\n      [b, name'),[b,'Café gratis',2,0]);
  // Read exactly the server component SQL, preserving its normal indentation.
  const readiness=source('lib/owner/start-guide.tsx').match(/query\(actor,`([\s\S]*?)`,\[businessId\]/)[1];
  assert.equal((await db.query(readiness,[b])).rows[0].reward,true);
  await scope('npr_v2_auth',owner);
  const {rows:[staff]}=await db.query('select nival_pr_private.manage_staff($1,null,$2,$3,true) id',[b,'Luis','scrypt$'+'a'.repeat(32)+'$'+'b'.repeat(128)]);
  await scope('npr_v2_auth');
  const business=await publicData();assert.equal(business.active,true);assert.equal(business.rewards[0].name,'Café gratis');
  const token='a'.repeat(64),{rows:[customer]}=await db.query('select nival_pr_private.enroll_customer_legal($1,$2,$3,$4,false) id',['primer-cliente','María','525500001234',token]);const c=customer.id;
  const card=async(h=token)=>(await db.query('select nival_pr_private.customer_card($1,$2) data',[b,h])).rows[0].data;
  assert.equal((await card()).balance,0);assert.equal((await card()).manual_code.length,8);
  await scope('npr_v2_owner',owner);
  const operation='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
  const visit=sql('app/api/staff/movement/route.ts',"insert into nival_pr.point_ledger(business_id,customer_id,type,points,staff_id,operation_id)",'"\n        :');
  await db.query(visit,[b,c,owner,operation]);
  await assert.rejects(db.query(visit,[b,c,owner,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb']),/Limite diario|Visita demasiado reciente/);
  await scope('npr_v2_auth',staff.id);assert.equal((await card()).balance,2);
  assert.equal((await db.query('select nival_pr_private.staff_customer_code($1,$2) data',[b,(await card()).manual_code])).rows[0].data.id,c);
  const path=b+'/'+c+'/cccccccc-cccc-4ccc-8ccc-cccccccccccc.png';
  await db.query('select nival_pr_private.store_photo($1,$2,$3,$4,$5)',[b,c,path,Buffer.from('1234567890123456').toString('base64'),'image/png']);
  await scope('npr_v2_staff',staff.id);
  const redeem=sql('app/api/staff/movement/route.ts',"insert into nival_pr.point_ledger(business_id,customer_id,type,points,staff_id,reward_id,evidence_path,operation_id)",'";');
  const {rows:[redemption]}=await db.query(redeem,[b,c,staff.id,reward.id,path,'dddddddd-dddd-4ddd-8ddd-dddddddddddd']);
  const rid=(await db.query('select id from nival_pr.redemptions where ledger_id=$1',[redemption.id])).rows[0].id;
  await scope('npr_v2_auth',owner);assert.equal((await card()).balance,0);
  await db.query('select nival_pr_private.review_redemption($1,$2,$3)',[b,rid,'reverse']);
  assert.equal((await card()).balance,2);
  await db.query('select nival_pr_private.issue_recovery($1,$2,$3)',[b,c,'b'.repeat(64)]);
  await scope('npr_v2_auth');await db.query('select nival_pr_private.consume_recovery($1,$2,$3)',['primer-cliente','b'.repeat(64),'c'.repeat(64)]);
  assert.equal(await card(),null);assert.equal((await card('c'.repeat(64))).balance,2);
  await scope('npr_v2_admin',admin);await db.query("update nival_pr.businesses set paid_until=now()-interval '1 second' where id=$1",[b]);
  await scope('npr_v2_auth');assert.equal(Boolean((await publicData()).active),false);
  await scope('npr_v2_owner',owner);assert.equal((await db.query('select sum(points)::int balance from nival_pr.point_ledger where customer_id=$1',[c])).rows[0].balance,2);
  await assert.rejects(db.query(visit,[b,c,owner,'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee']),/Servicio no activo/);
 }finally{await db.close();}
});
