import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {hashPin,verifyPin,sha256,randomToken,hintRole,signedHint} from '../lib/foundation/security.mjs';
const ids={a:'11111111-1111-4111-8111-111111111111',b:'22222222-2222-4222-8222-222222222222',admin:'33333333-3333-4333-8333-333333333333',staff:'44444444-4444-4444-8444-444444444444'};
const ba='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',bb='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',ca='aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',cb='bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb';
async function setup(){const db=new PGlite();await db.exec(`create schema neon_auth;create table neon_auth."user"(id uuid primary key);`);await db.exec(readFileSync('database/foundation-neon.sql','utf8'));await db.exec(`insert into neon_auth."user" values('${ids.a}'),('${ids.b}'),('${ids.admin}'),('${ids.staff}');insert into nival_pr.profiles(id,role,full_name) values('${ids.a}','owner','A'),('${ids.b}','owner','B'),('${ids.admin}','superadmin','Admin'),('${ids.staff}','staff','Mesero');insert into nival_pr.businesses(id,slug,name,status,paid_until) values('${ba}','cafe-demo','Cafe Demo','activo',now()+interval '30 days'),('${bb}','otro-negocio','Otro Negocio','activo',now()+interval '30 days');insert into nival_pr.memberships values('${ids.a}','${ba}','owner',null,true),('${ids.b}','${bb}','owner',null,true),('${ids.staff}','${ba}','staff','hash-secreto',true);insert into nival_pr.programs(business_id,name,rules) values('${ba}','Cafe','{"min_hours_between_visits":0,"max_visits_per_day":100}'),('${bb}','Otro','{"min_hours_between_visits":4,"max_visits_per_day":2}');insert into nival_pr.rewards(program_id,name,points_cost,position) select id,'Cafe gratis',2,0 from nival_pr.programs;insert into nival_pr.customers(id,business_id,phone,name,device_token_hash,consent_at) values('${ca}','${ba}','5512345678','Cliente A','${'a'.repeat(64)}',now()),('${cb}','${bb}','5512345678','Cliente B','${'b'.repeat(64)}',now());`);return db;}
async function as(db,role,id='',hash=''){await db.exec(`reset role;set role ${role};`);await db.query("select set_config('npr.user_id',$1,false),set_config('npr.device_token_hash',$2,false)",[id,hash]);}
const visit=(db,c=ca,b=ba,id=ids.staff,points=1)=>db.query("insert into nival_pr.point_ledger(business_id,customer_id,type,points,staff_id) values($1,$2,'visit',$3,$4) returning id",[b,c,points,id]);
test('RLS in all 21 tables; owners isolated and cannot promote roles or access hashes',async()=>{const db=await setup();try{await as(db,'npr_v2_owner',ids.a);assert.equal((await db.query('select id from nival_pr.businesses')).rows.length,1);assert.equal((await db.query('select id from nival_pr.customers')).rows[0].id,ca);assert.equal((await db.query('select id from nival_pr.businesses where id=$1',[bb])).rows.length,0);await assert.rejects(db.query('select device_token_hash from nival_pr.customers'),/permission denied/);await assert.rejects(db.query('select pin_hash from nival_pr.memberships'),/permission denied/);await assert.rejects(db.query("update nival_pr.profiles set role='superadmin'"),/permission denied/);await assert.rejects(db.query("insert into nival_pr.customers(business_id,phone,name) values($1,'5599999999','Ajeno')",[bb]),/row-level security/);await db.exec('reset role');assert.equal((await db.query("select count(*)::int as n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('nival_pr','nival_pr_private') and c.relkind='r' and c.relrowsecurity")).rows[0].n,21);}finally{await db.close();}});
test('staff has no finances, reports, phone or token; inactive membership loses scope',async()=>{const db=await setup();try{await as(db,'npr_v2_staff',ids.staff);for(const table of ['payments','review_reports','audit_log','activation_codes','site_content'])await assert.rejects(db.query('select * from nival_pr.'+table),/permission denied/);await assert.rejects(db.query('select phone from nival_pr.customers'),/permission denied/);await assert.rejects(db.query('select device_token_hash from nival_pr.customers'),/permission denied/);assert.equal((await db.query('select id from nival_pr.customers')).rows.length,1);await assert.rejects(visit(db,cb,bb),/row-level security/);await db.exec('reset role');await db.query('update nival_pr.memberships set active=false where user_id=$1',[ids.staff]);await as(db,'npr_v2_staff',ids.staff);assert.equal((await db.query('select id from nival_pr.customers')).rows.length,0);await assert.rejects(visit(db),/row-level security/);}finally{await db.close();}});
test('points amount validated, no negative balance, cross-business reward and identity rejected',async()=>{const db=await setup();try{await as(db,'npr_v2_staff',ids.staff);await assert.rejects(visit(db,ca,ba,ids.staff,999),/Cantidad de puntos invalida/);await assert.rejects(visit(db,ca,ba,ids.a),/row-level security/);const own=(await db.query('select id from nival_pr.rewards')).rows[0].id;const redeem=(r=own)=>db.query("insert into nival_pr.point_ledger(business_id,customer_id,type,points,staff_id,reward_id) values($1,$2,'redeem',-2,$3,$4)",[ba,ca,ids.staff,r]);await assert.rejects(redeem(),/Saldo insuficiente/);await visit(db);await visit(db);assert.equal(Number((await db.query('select nival_pr.point_balance($1) as points',[ca])).rows[0].points),2);await redeem();assert.equal(Number((await db.query('select nival_pr.point_balance($1) as points',[ca])).rows[0].points),0);assert.equal((await db.query('select id from nival_pr.redemptions')).rows.length,1);await assert.rejects(redeem(),/Saldo insuficiente/);await db.exec('reset role');const other=(await db.query('select r.id from nival_pr.rewards r join nival_pr.programs p on p.id=r.program_id where p.business_id=$1',[bb])).rows[0].id;await as(db,'npr_v2_staff',ids.staff);await assert.rejects(redeem(other),/Premio invalido/);}finally{await db.close();}});
test('immutable ledger denies update/delete/truncate even to infrastructure role with trigger enabled',async()=>{const db=await setup();try{await as(db,'npr_v2_staff',ids.staff);await visit(db);for(const role of ['npr_v2_owner','npr_v2_staff','npr_v2_admin']){await as(db,role,role==='npr_v2_owner'?ids.a:role==='npr_v2_admin'?ids.admin:ids.staff);for(const sql of ['update nival_pr.point_ledger set points=20','delete from nival_pr.point_ledger','truncate nival_pr.point_ledger'])await assert.rejects(db.query(sql),/permission denied|Registro inmutable/);}await db.exec('reset role');await assert.rejects(db.query('update nival_pr.point_ledger set points=2'),/Registro inmutable/);await assert.rejects(db.query('delete from nival_pr.point_ledger'),/Registro inmutable/);assert.equal((await db.query('select points from nival_pr.point_ledger')).rows[0].points,1);}finally{await db.close();}});
test('status change audited, same status no extra log, owner cannot update status',async()=>{const db=await setup();try{await as(db,'npr_v2_owner',ids.a);await assert.rejects(db.query("update nival_pr.businesses set status='pausado'"),/permission denied/);await as(db,'npr_v2_admin',ids.admin);await db.query("update nival_pr.businesses set status='pausado' where id=$1",[ba]);await db.query("update nival_pr.businesses set status='pausado' where id=$1",[ba]);const logs=(await db.query('select actor_id,business_id,data from nival_pr.audit_log')).rows;assert.equal(logs.length,1);assert.equal(logs[0].actor_id,ids.admin);assert.equal(logs[0].data.old,'activo');assert.equal(logs[0].data.new,'pausado');await assert.rejects(db.query('delete from nival_pr.audit_log'),/permission denied|Registro inmutable/);}finally{await db.close();}});
test('customer token isolates balance, does not disclose name/phone, can be revoked',async()=>{const db=await setup();try{await as(db,'npr_v2_customer','','a'.repeat(64));assert.equal((await db.query('select id from nival_pr.customers')).rows[0].id,ca);await assert.rejects(db.query('select name,phone from nival_pr.customers'),/permission denied/);await assert.rejects(db.query('select * from nival_pr.payments'),/permission denied/);await db.exec('reset role');await db.query('update nival_pr.customers set device_token_hash=null where id=$1',[ca]);await as(db,'npr_v2_customer','','a'.repeat(64));assert.equal((await db.query('select id from nival_pr.customers')).rows.length,0);}finally{await db.close();}});
test('PIN rate limit, session expiration/revocation and pin change',async()=>{const db=await setup();try{await as(db,'npr_v2_auth');for(let i=0;i<5;i++)assert.equal((await db.query('select nival_pr_private.claim_pin_attempt($1) as ok',['c'.repeat(64)])).rows[0].ok,true);assert.equal((await db.query('select nival_pr_private.claim_pin_attempt($1) as ok',['c'.repeat(64)])).rows[0].ok,false);await db.query('select nival_pr_private.issue_staff_session($1,$2,$3)',[ids.staff,ba,'d'.repeat(64)]);assert.equal((await db.query('select * from nival_pr_private.staff_session($1)',['d'.repeat(64)])).rows.length,1);await db.exec('reset role');await db.query("update nival_pr.memberships set pin_hash='changed' where user_id=$1",[ids.staff]);await as(db,'npr_v2_auth');assert.equal((await db.query('select * from nival_pr_private.staff_session($1)',['d'.repeat(64)])).rows.length,0);await db.query('select nival_pr_private.revoke_staff_session($1)',['d'.repeat(64)]);await assert.rejects(db.query('select * from nival_pr_private.staff_sessions'),/permission denied/);}finally{await db.close();}});
test('visit limits enforced and paused businesses reject writes',async()=>{const db=await setup();try{await db.query('update nival_pr.programs set rules=$1::jsonb where business_id=$2',[JSON.stringify({min_hours_between_visits:4,max_visits_per_day:2}),ba]);await as(db,'npr_v2_staff',ids.staff);await visit(db);await assert.rejects(visit(db),/Visita demasiado reciente/);await db.exec('reset role');await db.query("update nival_pr.businesses set status='pausado' where id=$1",[ba]);await as(db,'npr_v2_staff',ids.staff);await assert.rejects(visit(db),/Servicio no activo/);}finally{await db.close();}});
test('public phone registration does not reveal an existing account; owner cannot rotate other business token',async()=>{const db=await setup();try{await as(db,'npr_v2_auth');await assert.rejects(db.query('select nival_pr_private.enroll_customer($1,$2,$3,$4)',['cafe-demo','Falso','5512345678','f'.repeat(64)]),/unique constraint/);await db.query("select set_config('npr.user_id',$1,false)",[ids.a]);await assert.rejects(db.query('select nival_pr_private.rotate_customer_token($1,$2,$3)',[bb,cb,'f'.repeat(64)]),/Owner required/);}finally{await db.close();}});
test('PIN hashes and signed role hints resist guessing/tampering',async()=>{const hash=await hashPin('123456');assert.equal(await verifyPin('123456',hash),true);assert.equal(await verifyPin('123457',hash),false);assert.equal(await verifyPin('123456','broken'),false);assert.notEqual(hash,await hashPin('123456'));const secret='x'.repeat(32),hint=signedHint('owner',secret);assert.equal(hintRole(hint,secret),'owner');assert.equal(hintRole(hint+'x',secret),null);assert.equal(hintRole(hint,'y'.repeat(32)),null);assert.equal(sha256(randomToken()).length,64);});

test('choose locks one customer goal; sequence enforces next reward',async()=>{const db=await setup();try{await db.query("insert into nival_pr.rewards(program_id,name,points_cost,position) select id,'Segundo premio',2,1 from nival_pr.programs where business_id=$1",[ba]);const rewards=(await db.query('select r.id from nival_pr.rewards r join nival_pr.programs p on p.id=r.program_id where p.business_id=$1 order by r.position',[ba])).rows;await db.query("update nival_pr.programs set mode='choose' where business_id=$1",[ba]);await as(db,'npr_v2_staff',ids.staff);for(let i=0;i<4;i++)await visit(db);const redeem=r=>db.query("insert into nival_pr.point_ledger(business_id,customer_id,type,points,staff_id,reward_id) values($1,$2,'redeem',-2,$3,$4)",[ba,ca,ids.staff,r]);await assert.rejects(redeem(rewards[0].id),/Selecciona tu meta/);await as(db,'npr_v2_auth');await db.query('select nival_pr_private.choose_goal($1,$2,$3)',[ba,'a'.repeat(64),rewards[0].id]);await assert.rejects(db.query('select nival_pr_private.choose_goal($1,$2,$3)',[ba,'a'.repeat(64),rewards[1].id]),/Goal locked/);await db.exec('reset role');await db.query("update nival_pr.programs set mode='sequence' where business_id=$1",[ba]);await as(db,'npr_v2_staff',ids.staff);await assert.rejects(redeem(rewards[1].id),/Premio fuera de secuencia/);await redeem(rewards[0].id);await redeem(rewards[1].id);await assert.rejects(redeem(rewards[0].id),/Premio fuera de secuencia/);}finally{await db.close();}});
test('audit rolls back with business state transaction and can only read own business audit',async()=>{const db=await setup();try{await as(db,'npr_v2_admin',ids.admin);await db.exec('begin');await db.query("update nival_pr.businesses set status='pausado' where id=$1",[bb]);await db.exec('rollback');assert.equal((await db.query('select id from nival_pr.audit_log')).rows.length,0);await db.query("update nival_pr.businesses set status='pausado' where id=$1",[bb]);await as(db,'npr_v2_owner',ids.a);assert.equal((await db.query('select id from nival_pr.audit_log')).rows.length,0);await as(db,'npr_v2_owner',ids.b);assert.equal((await db.query('select id from nival_pr.audit_log')).rows.length,1);}finally{await db.close();}});
test('expired staff sessions fail and owner role cannot use staff-only membership',async()=>{const db=await setup();try{await as(db,'npr_v2_auth');await db.query('select nival_pr_private.issue_staff_session($1,$2,$3)',[ids.staff,ba,'d'.repeat(64)]);await db.exec('reset role');await db.query("update nival_pr_private.staff_sessions set expires_at=now()-interval '1 hour'");await as(db,'npr_v2_auth');assert.equal((await db.query('select * from nival_pr_private.staff_session($1)',['d'.repeat(64)])).rows.length,0);await db.exec('reset role');await db.query("update nival_pr.memberships set role='staff' where user_id=$1",[ids.a]);await as(db,'npr_v2_owner',ids.a);assert.equal((await db.query('select id from nival_pr.businesses')).rows.length,0);}finally{await db.close();}});

 test('recurring completion is atomic and repeat completion creates no duplicate',async()=>{const db=await setup();try{
 await as(db,'npr_v2_admin',ids.admin);
 const task=(await db.query("insert into nival_pr.tasks(business_id,title,recurrence,due_date) values($1,'Cobrar mensualidad','weekly',current_date-30) returning id",[ba])).rows[0];
 const source=readFileSync('lib/admin/actions.ts','utf8');
 const sql=source.match(/with changed as \([\s\S]*?from changed returning id/)[0];
 await db.query(sql,[task.id,'completada',ids.admin]);
 await db.query(sql,[task.id,'completada',ids.admin]);
 const tasks=(await db.query("select status,due_date from nival_pr.tasks where title='Cobrar mensualidad'")).rows;
 assert.equal(tasks.length,2);assert.equal(tasks.filter(t=>t.status==='pendiente').length,1);
 assert.equal((await db.query("select count(*)::int n from nival_pr.audit_log where action='task.status_changed'")).rows[0].n,1);
 }finally{await db.close();}});

test('activation codes expire and a claimed code activates only once',async()=>{const db=await setup();try{await db.exec(readFileSync('database/reputation-v6.sql','utf8'));
 await db.query("insert into nival_pr.activation_codes(code,business_id,plan_id,expires_at,created_by) select 'NIV-AAAA-BBBB',$1,id,now()+interval '1 hour',$2 from nival_pr.plans limit 1",[ba,ids.admin]);
 const source=readFileSync('lib/admin/actions.ts','utf8');const sql=source.match(/with claimed as \([\s\S]*?select \* from activated/)[0];
 assert.equal((await db.query(sql,['NIV-AAAA-BBBB',ba])).rows.length,1);
 assert.equal((await db.query(sql,['NIV-AAAA-BBBB',ba])).rows.length,0);
 await db.query("insert into nival_pr.activation_codes(code,business_id,plan_id,expires_at,created_by) select 'NIV-CCCC-DDDD',$1,id,now()-interval '1 hour',$2 from nival_pr.plans limit 1",[ba,ids.admin]);
 assert.equal((await db.query(sql,['NIV-CCCC-DDDD',ba])).rows.length,0);
 }finally{await db.close();}});

test('payment records initial payment without starting service; renewal extends from expiry',async()=>{
 const db=await setup();try{
 await db.exec(readFileSync('database/reputation-v6.sql','utf8'));
 await db.query("update nival_pr.businesses set status='registrado',paid_until=null where id=$1",[ba]);
 await as(db,'npr_v2_admin',ids.admin);
 const source=readFileSync('lib/admin/actions.ts','utf8').split('export async function registerPayment30')[1].split('export async function generateActivationCode')[0];
 const sql=source.match(/text:`([\s\S]*?)`,values:/)[1];
 const {rows:[payment]}=await db.query(sql,[ba,399,'transferencia','TEST',ids.admin]);assert.ok(payment.id);
 const {rows:[b]}=await db.query('select * from nival_pr.businesses where id=$1',[ba]);assert.equal(b.status,'pago_pendiente');assert.equal(b.paid_until,null);
 await db.query("update nival_pr.businesses set status='activo',paid_until=now()+interval '10 days' where id=$1",[ba]);
 const before=(await db.query('select paid_until from nival_pr.businesses where id=$1',[ba])).rows[0].paid_until;
 await db.query(sql,[ba,399,'transferencia','RENEW',ids.admin]);
 const after=(await db.query('select paid_until from nival_pr.businesses where id=$1',[ba])).rows[0].paid_until;
 assert.equal((new Date(after)-new Date(before))/86400000,30);
 }finally{await db.close();}
});
