import {AdminNavigation} from '../../../lib/admin/navigation';
import {entitlements} from '../../../lib/foundation/entitlements.mjs';
import {GoogleReportForm} from '../../../lib/owner/google-form';
import {requireAdminRole} from '../../../lib/foundation/session';
import {query} from '../../../lib/foundation/db';
import {ActionForm} from '../../../lib/foundation/forms';
import {ReviewImporter,CopyReply,ReportPeriod} from '../../../lib/reputation/importer';
import {ReportView} from '../../../lib/reputation/report-view';
import {generateReport,approveReport,recordReportSent,recordPublishedReply,editImportedReview} from '../../../lib/reputation/actions';
import {serviceWindow} from '../../../lib/reputation/engine.mjs';
export const dynamic='force-dynamic';
export default async function Reports({searchParams}:{searchParams:Promise<{business?:string;report?:string}>}){
 const actor=await requireAdminRole(),params=await searchParams;
 const businesses=await query(actor,"select b.*,coalesce(p.features,'{}'::jsonb)||jsonb_build_object('review_limit',coalesce(nival_pr_private.plan_review_limit(p.id),0)) features from nival_pr.businesses b left join nival_pr.plans p on p.id=b.plan_id order by b.name");
 const b=params.business?businesses.find(b=>b.id===params.business):businesses[0];
 if(!b)return <main className="dashboard"><h1>Primero registra un negocio</h1><a href="/admin">Volver</a></main>;
 const access=entitlements(b);
 const reviews=await query(actor,"select rv.*,to_char(rv.reviewed_on,'YYYY-MM-DD') as reviewed_on_iso from nival_pr.reviews rv where rv.business_id=$1 order by rv.reviewed_on desc,rv.id desc limit 200",[b.id]);
 const reports=await query(actor,"select r.*,b.name business_name,to_char(period_start,'YYYY-MM-DD') period_start,to_char(period_end,'YYYY-MM-DD') period_end from nival_pr.generated_reports r join nival_pr.businesses b on b.id=r.business_id where r.business_id=$1 order by r.created_at desc limit 40",[b.id]);
 const window=serviceWindow(b);const used=window?(await query(actor,'select count(*)::int used from nival_pr.reviews where business_id=$1 and published_at>=$2 and published_at<$3',[b.id,window.start,window.end]))[0].used:0;
 const report=reports.find(r=>r.id===params.report)||reports[0],today=new Date().toISOString().slice(0,10),start=new Date(Date.now()-7*86400000).toISOString().slice(0,10);
 return <main className="dashboard adminShell"><div className="adminWorkspace"><AdminNavigation view="reportes"/><div className="adminContent"><header className="dashHead"><div><small>NIVAL · GOOGLE</small><h1>Google y reseñas</h1></div><a href="/admin">Centro de operación</a></header><form><label>Negocio<select name="business" defaultValue={b.id}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name} · {b.slug}</option>)}</select></label><button>Abrir negocio</button></form><section className="reviewBox"><h2>{b.name}</h2><p>Código: {b.slug} · Teléfono: {b.phone||'Sin teléfono'} · Correo: {b.email||'Sin correo'}</p><p>Respuestas publicadas en el periodo: {used} de {b.features?.review_limit??'Sin cupo configurado'}. No se acumulan respuestas no utilizadas.</p>{access.replies&&Number(used)>=Number(b.features?.review_limit)&&<p role="status">Cupo agotado: las nuevas respuestas quedan pendientes de renovación o ampliación autorizada.</p>}</section>{!access.reviews&&<p className="ownerEmpty">Historial conservado. El seguimiento y los informes nuevos están suspendidos hasta contratar y activar $399 o $499.</p>}{access.reviews&&<><ReviewImporter businessId={b.id}/><details className="reviewBox"><summary>Actualizar métricas de Google para el panel del negocio</summary><GoogleReportForm businesses={[b as {id:string;name:string}]}/></details>
 <section className="reviewBox"><h2>Generar un reporte</h2><p>El diagnóstico inicial cubre los últimos tres meses. Carga la calificación, el total global y el alcance visible en Google; Nival no los deduce de la muestra de reseñas.</p><ActionForm action={generateReport} label="Generar borrador"><input type="hidden" name="businessId" value={b.id}/><ReportPeriod/><label>Calificación actual en Google<input name="rating" type="number" min="1" max="5" step="0.1"/></label><label>Total actual en Google<input name="total" type="number" min="0" step="1"/></label><h3>Alcance del periodo desde Google</h3><p>Captura estas cifras manualmente desde el Perfil de Negocio. Las dejamos identificadas como datos ingresados, no importados automáticamente.</p><label>Impresiones en Búsqueda<input name="searchImpressions" type="number" min="0" step="1"/></label><label>Impresiones en Maps<input name="mapsImpressions" type="number" min="0" step="1"/></label><label>Llamadas desde la ficha<input name="calls" type="number" min="0" step="1"/></label><label>Clics al sitio web<input name="websiteClicks" type="number" min="0" step="1"/></label><label>Solicitudes de cómo llegar<input name="directionRequests" type="number" min="0" step="1"/></label></ActionForm></section>
 </>}
 {report&&<><ReportView report={report}/>{report.status==='draft'&&access.reviews?<ActionForm action={approveReport} label="Aprobar y publicar en el panel"><input type="hidden" name="reportId" value={report.id}/><label><input name="confirmed" type="checkbox" required/> Revisé los datos y recomendaciones. Para corregirlos, actualizo las reseñas y genero otro borrador.</label></ActionForm>:<section className="reviewBox"><p>{report.sent_at?'Envío registrado':'PDF listo; envío pendiente'}</p>{b.email&&<a href={'mailto:'+b.email+'?subject='+encodeURIComponent('Reporte Nival · '+b.name)}>Preparar correo (adjunta el PDF descargado)</a>}{b.phone&&<p><a href={'https://wa.me/'+(b.phone.startsWith('52')?b.phone:'52'+b.phone)+'?text='+encodeURIComponent('Hola, ya está disponible el reporte de '+b.name+' en tu panel de Nival. Te comparto el PDF.')} target="_blank" rel="noreferrer">Abrir WhatsApp (adjunta el PDF)</a></p>}{access.reviews&&<ActionForm action={recordReportSent} label="Marcar como enviado"><input type="hidden" name="reportId" value={report.id}/></ActionForm>}</section>}</>}
 <section className="reviewBox"><h2>Historial de reportes</h2>{reports.map(r=><p key={r.id}><a href={'?business='+b.id+'&report='+r.id}>{r.kind} · {String(r.period_start).slice(0,10)} · {r.status==='approved'?'Aprobado':'Borrador'}</a></p>)}</section>
 <section className="reviewBox"><h2>Reseñas y respuestas</h2><p>Los borradores son plantillas editables. Revisa el contexto; consulta al dueño si hay una queja delicada. Copiar una respuesta no la publica en Google.</p>{reviews.map(r=><article className="customerRow" key={r.id}><h3>{r.reviewer} · {r.stars} estrellas</h3><small>Estado de respuesta: {r.response_status|| (r.published_at?'published':r.response_draft?'drafted':'pending')} · {r.reviewed_on_iso}</small><p>{r.body||'Sin texto'}</p>{access.reviews&&<details><summary>Corregir datos cargados</summary><ActionForm action={editImportedReview} label="Guardar corrección"><input type="hidden" name="reviewId" value={r.id}/><label>Autor<input name="reviewer" required maxLength={120} defaultValue={r.reviewer}/></label><label>Estrellas<select name="stars" defaultValue={r.stars}>{[5,4,3,2,1].map(n=><option key={n}>{n}</option>)}</select></label><label>Fecha<input name="reviewed_on" type="date" required defaultValue={r.reviewed_on_iso}/></label><label>Texto<textarea name="body" maxLength={10000} defaultValue={r.body}/></label></ActionForm></details>}{r.published_at?<p>Publicada: {r.published_response}</p>:access.replies?<><CopyReply text={r.response_draft||''}/><ActionForm action={recordPublishedReply} label="Registrar respuesta publicada"><input type="hidden" name="reviewId" value={r.id}/><label className="wide">Respuesta que publicaste<textarea name="reply" required maxLength={10000} defaultValue={r.response_draft||''}/></label><label><input type="checkbox" name="confirmed" required/> Confirmo que ya la publiqué en Google</label></ActionForm></>:<p>{access.reviews?'Este plan incluye seguimiento, sin respuestas manuales.':'Reseña histórica · solo lectura.'}</p>}</article>)}</section></div></div></main>;
}
