'use client';
import {useActionState} from 'react';
import {createBusiness,addCustomer,recordMovement,updateReward,type ActionResult} from './actions';
const initial:ActionResult={};
function Status({state}:{state:ActionResult}){return <p role="status" className={state.error?'error':''}>{state.error||state.success}</p>}
export function BusinessForm(){const[state,action,pending]=useActionState(createBusiness,initial);return <form className="configGrid" action={action}><label>Nombre del negocio<input name="name" required maxLength={150}/></label><button disabled={pending}>{pending?'Guardando…':'Crear mi negocio'}</button><Status state={state}/></form>}
export function CustomerForm(){const[state,action,pending]=useActionState(addCustomer,initial);return <form className="configGrid" action={action}><label>Nombre del cliente<input name="name" required maxLength={100}/></label><label>Teléfono (opcional)<input name="phone" type="tel" maxLength={20}/></label><button disabled={pending}>{pending?'Guardando…':'Registrar cliente'}</button><Status state={state}/></form>}
export function MovementForm({id,canRedeem,goal}:{id:string;canRedeem:boolean;goal:number}){const[state,action,pending]=useActionState(recordMovement,initial);return <form action={action} onSubmit={event=>{const submitter=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;if(submitter?.value==='redeem'&&!window.confirm(`¿Entregar el premio y descontar ${goal} puntos?`))event.preventDefault();}}><input name="customerId" type="hidden" value={id}/><div className="actions"><button name="kind" value="visit" disabled={pending}>Visita +1</button><button name="kind" value="redeem" disabled={pending||!canRedeem}>Canjear {goal} pts</button></div><Status state={state}/></form>}
export function RewardForm({goal,reward,risk}:{goal:number;reward:string;risk:number}){const[state,action,pending]=useActionState(updateReward,initial);return <form className="configGrid" action={action}><label>Meta de puntos<input name="goal" type="number" min="1" max="100000" step="1" required defaultValue={goal}/></label><label>Premio<input name="reward" maxLength={150} required defaultValue={reward}/></label><label>Días para considerar en riesgo<input name="risk" type="number" min="1" max="365" step="1" required defaultValue={risk}/></label><button disabled={pending}>Guardar recompensa</button><Status state={state}/></form>}
