export const landingContent = {
  brand: "Nival",
  brandHomeLabel: "Nival, inicio",
  navigation: {
    label: "Navegación principal",
    product: "Puntos + Reseñas",
    demo: "Ver demo",
    access: "Acceso a mi negocio",
  },
  hero: {
    eyebrow: "Para cafeterías y restaurantes",
    titleStart: "Haz que tus clientes",
    titleEnd: "vuelvan",
    subtitle: "Más visitas frecuentes y más reseñas de Google para tu negocio.",
    whatsappLabel: "Cotizar por WhatsApp",
    whatsappPhone: "525539044788",
    whatsappMessage: "Hola Nival, quiero cotizar Puntos + Reseñas para mi negocio.",
    quickNote: "Para cafeterías y restaurantes de barrio.",
    visualLabel: "Vista de cliente · ejemplo ficticio",
    visualAlt: "Ejemplo ficticio de una tarjeta de puntos en el celular y una nueva reseña de cinco estrellas",
    cornerNumber: "01",
    cornerLabel: "Clientes que vuelven",
    businessName: "Café de la Esquina",
    businessInitial: "C",
    productLabel: "Café · puntos",
    phoneTime: "9:41",
    greeting: "Hola",
    customerName: "Mariana",
    visitsLabel: "Visitas",
    visitsCount: "3 de 6",
    reward: "Una bebida de regalo",
    visitRecorded: "Visita registrada",
    pointsBadge: "+1 visita",
    reviewTitle: "Nueva reseña",
    reviewAuthor: "Mariana G.",
    reviewText: "Volver por mi café ahora tiene premio.",
    reviewTime: "ahora",
    reviewStarsLabel: "5 de 5 estrellas",
  },
} as const;
