'use client';
import LandingIcon from './landing-icon';
import {useState} from 'react';
type Benefit={symbol:string;label:string;detail:string};
export default function LandingInteractions({mode,wa,items=[]}:{mode:'menu'|'arrows'|'benefits'|'billing';wa?:string;items?:Benefit[]}){
 const [open,setOpen]=useState(false);const [selected,setSelected]=useState<number|null>(0);
 if(mode==='menu')return <div className="refMobileMenu"><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>Menú</button>{open&&<nav className="refMobileLinks"><a href="#como" onClick={()=>setOpen(false)}>Cómo funciona</a><a href="#precios" onClick={()=>setOpen(false)}>Precios</a><a href="#preguntas" onClick={()=>setOpen(false)}>Preguntas frecuentes</a><a href="#contacto" onClick={()=>setOpen(false)}>Contacto</a><a href="/demo">Ver demo</a><a href={wa} onClick={()=>setOpen(false)}>Pedir informes</a><a href="/acceso?modo=registro" onClick={()=>setOpen(false)}>Registrarse</a><a href="/acceso" onClick={()=>setOpen(false)}>Acceso a negocios</a><a href="/staff/acceso" onClick={()=>setOpen(false)}>Acceso de personal</a><a href="/acceso-administrador" onClick={()=>setOpen(false)}>Administrador Nival</a></nav>}</div>;
 if(mode==='arrows')return <div className="refArrows"><button type="button" aria-label="Anterior" onClick={()=>document.getElementById('refSteps')?.scrollBy({left:-270,behavior:'smooth'})}><LandingIcon name="arrow-left"/></button><button type="button" aria-label="Siguiente" onClick={()=>document.getElementById('refSteps')?.scrollBy({left:270,behavior:'smooth'})}><LandingIcon name="arrow"/></button></div>;
 if(mode==='benefits')return <div className="refBenefitPicker"><div className="refBenefitGrid">{items.map((item,index)=><div className="refBenefitItem" key={item.label}><button type="button" className={selected===index?'isSelected':''} aria-expanded={selected===index} aria-controls={`benefit-detail-${index}`} onClick={()=>setSelected(selected===index?null:index)}><span><LandingIcon name={item.symbol}/></span><p>{item.label}</p><LandingIcon name="arrow"/></button>{selected===index&&<div className="refBenefitWhy" id={`benefit-detail-${index}`} role="region" aria-label={`Por qué importa: ${item.label}`}><span><LandingIcon name={item.symbol}/></span><div><small>¿POR QUÉ IMPORTA?</small><strong>{item.label}</strong><p>{item.detail}</p></div></div>}</div>)}</div></div>;
 return null;
}
