import {foundationEnabled,systemQuery} from '../lib/foundation/db';

const defaults={price:'$399 MXN/mes',whatsapp:'5539044788'};
export const revalidate=0;
export default async function Home(){
 let values:{[key:string]:string}={...defaults};
 if(foundationEnabled()){try{const rows=await systemQuery("select key,value_published from nival_pr.site_content where value_published is not null");for(const row of rows)if(row.key in values)values[row.key]=String(row.value_published?.text??values[row.key]);}catch{}}
 const phone=values.whatsapp.replace(/\D/g,'')||defaults.whatsapp;
 const wa=`https://wa.me/52${phone}?text=${encodeURIComponent('Hola, quiero conocer Nival Puntos + Reseñas para mi negocio.')}`;
 return <main className="millionSite">
  <nav className="millionNav"><a className="millionBrand" href="/"><span>N</span><b>NIVAL</b></a><div className="millionNavLinks"><a href="#producto">Producto</a><a href="/demo">Demo</a><a href="/acceso">Entrar</a><a className="millionNavCta" href="/registro">Empezar <i>↗</i></a></div></nav>

  <section className="millionHero">
   <div className="millionGlow glowOne"/><div className="millionGlow glowTwo"/>
   <div className="millionHeroCopy"><div className="millionKicker"><i/> LEALTAD, SIN FRICCIÓN</div><h1>Haz que una visita<br/><em>se convierta en hábito.</em></h1><p>Nival convierte clientes ocasionales en clientes frecuentes con puntos digitales y una reputación que puedes entender.</p><div className="millionActions"><a className="millionPrimary" href="/registro">Registrar mi negocio <span>↗</span></a><a className="millionDemo" href="/demo"><i>▶</i><span><small>MIRA CÓMO FUNCIONA</small>Ver demo interactiva</span></a></div><div className="millionProof"><span>Sin app</span><i/> <span>QR + NFC</span><i/> <span>Listo en minutos</span></div></div>
   <div className="millionStage" aria-label="Experiencia Nival"><div className="stageHalo"/><div className="millionPhone"><div className="phoneChrome"><span>9:41</span><i>● ● ▰</i></div><div className="loyaltyBrand"><div>N</div><span>CAFÉ<br/><b>NIVAL</b></span></div><div className="loyaltyCenter"><small>TUS PUNTOS</small><strong>06</strong><p>Dos visitas más y el café va por nuestra cuenta.</p></div><div className="luxProgress"><i/><i/><i/><i/><i/><i/><i className="empty"/><i className="empty"/></div><div className="phoneReward"><span>PRÓXIMO PREMIO</span><b>☕ Café de la casa</b></div></div><div className="luxToast"><span>✓</span><div><small>AHORA</small><b>+1 visita registrada</b></div></div><div className="luxMetric"><small>CLIENTES QUE VUELVEN</small><strong>+31%</strong><span>↗ este mes</span></div></div>
   <div className="scrollCue"><span>DESCUBRE NIVAL</span><i/></div>
  </section>

  <section className="millionManifesto"><p>Tu negocio no necesita otra app.</p><h2>Necesita una razón<br/>para <em>volver.</em></h2><div className="manifestoAside"><span>01 — LA IDEA</span><p>Cada visita cuenta. Cada punto acerca al cliente a algo que quiere. Y tú ves quién vuelve, quién se está alejando y qué está funcionando.</p></div></section>

  <section id="producto" className="millionProduct"><div className="productSticky"><span>02 — EL PRODUCTO</span><h2>Todo lo que importa.<br/><em>Nada que estorbe.</em></h2><p>Diseñado para usarse en segundos, no para aprenderse en horas.</p><a href="/demo">Explorar la demo <b>↗</b></a></div><div className="productStack">
   <article className="featureCard featureDark"><header><span>01</span><b>PUNTOS</b></header><div className="featureVisual pointsVisual"><div className="pointRing"><strong>7</strong><span>de 8</span></div><div className="pointText"><small>CASI AHÍ</small><b>Una visita más.</b><p>El premio ya se siente cerca.</p></div></div><footer>Una tarjeta digital que tu cliente realmente entiende.</footer></article>
   <article className="featureCard featureLight"><header><span>02</span><b>CLIENTES</b></header><div className="featureVisual clientVisual"><div className="clientBars"><i style={{height:'34%'}}/><i style={{height:'47%'}}/><i style={{height:'43%'}}/><i style={{height:'62%'}}/><i style={{height:'58%'}}/><i style={{height:'78%'}}/><i style={{height:'92%'}}/></div><div className="clientStat"><small>VISITAS</small><strong>184</strong><span>+24 esta semana</span></div></div><footer>Ve patrones, no hojas de cálculo.</footer></article>
   <article className="featureCard featureGold"><header><span>03</span><b>REPUTACIÓN</b></header><div className="featureVisual reviewVisual"><div><span>★★★★★</span><strong>4.8</strong><small>REPUTACIÓN ACTUAL</small></div><blockquote>“Ahora sé qué está diciendo la gente y qué tengo que mejorar.”</blockquote></div><footer>Reseñas convertidas en decisiones claras.</footer></article>
  </div></section>

  <section className="millionFlow"><div className="flowHead"><span>03 — ASÍ DE FÁCIL</span><h2>De cero a cliente frecuente<br/><em>en tres gestos.</em></h2></div><div className="flowRail"><article><b>01</b><div className="gestureIcon">⌁</div><h3>Acerca</h3><p>El cliente toca NFC o escanea el QR.</p></article><article><b>02</b><div className="gestureIcon">＋</div><h3>Suma</h3><p>Tu equipo registra la visita en segundos.</p></article><article><b>03</b><div className="gestureIcon">↻</div><h3>Vuelve</h3><p>El próximo premio siempre está a la vista.</p></article></div></section>

  <section className="millionDemoBand"><div className="demoAura"/><div className="demoCopy"><span>04 — PRUÉBALO</span><h2>No te lo<br/><em>imagines.</em></h2><p>Entra. Toca. Recorre el producto. La mejor explicación de Nival es Nival.</p><a className="millionPrimary inverted" href="/demo">Abrir demo interactiva <b>↗</b></a></div><div className="dashboardGlass"><div className="dashTop"><div><small>BUENAS TARDES</small><b>Café Nival</b></div><span>● EN VIVO</span></div><div className="dashHero"><small>VISITAS ESTE MES</small><strong>184</strong><span>↗ 18.4%</span></div><div className="dashGrid"><article><small>Frecuentes</small><b>62</b></article><article><small>Por volver</small><b>18</b></article><article><small>Reseñas</small><b>4.8 ★</b></article></div><div className="dashActivity"><i/><div><b>María volvió hoy</b><small>7 visitas · a 1 de su premio</small></div><span>AHORA</span></div></div></section>

  <section className="millionClose"><div className="closeMark">N</div><span>05 — EMPIEZA</span><h2>Haz que vuelvan.</h2><p>Una experiencia mejor para tus clientes.<br/>Una vista más clara para tu negocio.</p><div className="closeActions"><a className="millionPrimary" href="/registro">Registrar mi negocio <b>↗</b></a><a href={wa} target="_blank" rel="noreferrer">Hablar por WhatsApp</a></div><small>Puntos + Reseñas · {values.price}</small></section>

  <footer className="millionFooter"><div><a className="millionBrand" href="/"><span>N</span><b>NIVAL</b></a><p>Haz que vuelvan.</p></div><div><b>PRODUCTO</b><a href="/demo">Demo</a><a href="/registro">Registro</a><a href="/acceso">Entrar</a></div><div><b>LEGAL</b><a href="/terminos">Términos</a><a href="/privacidad">Privacidad</a></div><div><b>PERSONAL</b><a href="/staff/acceso">Acceso de equipo</a></div><small>© 2026 Nival Tech · México</small></footer>
 </main>
}