import LandingIcon from './landing-icon';
import LandingInteractions from './landing-interactions';
import WhatsAppFab from './whatsapp-fab';
import './landing-reference.css';

const wa = 'https://wa.me/525539044988?text=' + encodeURIComponent('Hola, quiero información de Nival Puntos + Reseñas');
const ReferenceImage = ({file,width,height,alt,className = ''}:{file:string;width:number;height:number;alt:string;className?:string}) => <img className={`refAsset ${className}`} width={width} height={height} alt={alt} src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E" style={{backgroundImage:`url("/assets/img/${file}"), linear-gradient(135deg, #d4ddd1, #8ba390 55%, #314d3b)`}}/>;
const Check = () => <svg viewBox="0 0 20 20" width="17" height="17" aria-hidden="true"><path d="m4 10 4 4 8-9" fill="none" stroke="currentColor" strokeWidth="2"/></svg>;
const features = [
  {symbol:'people',label:'Más clientes frecuentes',detail:'Un programa sencillo les da un motivo claro para elegirte de nuevo y convertir cada visita en una relación.'},
  {symbol:'trend',label:'Visitas que se repiten',detail:'Los puntos hacen visible el avance hacia un premio y mantienen tu negocio presente entre una visita y la siguiente.'},
  {symbol:'star',label:'Mejor reputación local',detail:'Una ficha clara y bien cuidada ayuda a que nuevos clientes te encuentren y conozcan la experiencia de otros.'},
  {symbol:'dollar',label:'Más oportunidades de venta',detail:'Promociones y recompensas relevantes pueden animar a tus clientes a probar algo más o volver pronto.'},
  {symbol:'gift',label:'Premios que sí motivan',detail:'Define recompensas atractivas para tu negocio y sencillas de entender para tus clientes.'},
  {symbol:'pin',label:'Más visibilidad en Google',detail:'Una presencia local completa facilita que las personas cercanas descubran cómo llegar, llamar y visitar.'},
  {symbol:'heart',label:'Clientes que se sienten valorados',detail:'Reconocer su preferencia crea una experiencia más cercana desde el primer registro.'},
  {symbol:'chart',label:'Una comunidad que crece',detail:'Consulta visitas, clientes nuevos y canjes desde tu panel para saber cómo avanza tu programa.'},
  {symbol:'shield',label:'Una experiencia fácil para todos',detail:'Tus clientes usan su tarjeta digital y el equipo registra puntos con un flujo sencillo.'}
];
const plans = [
 {name:'Nival Puntos',price:299,features:['Tarjeta digital con QR y personal','Registra visitas y canjea premios','Inteligencia de clientes y segmentos','Personalización básica de tarjeta']},
 {name:'Nival Esencial',price:399,popular:true,features:['Todo lo que incluye Nival Puntos','Hasta 30 respuestas por periodo activo de 30 días','Inteligencia de reseñas y recomendaciones','Reporte mensual de resultados']},
 {name:'Nival Plus',price:499,features:['Todo lo que incluye Nival Esencial','Hasta 100 respuestas por periodo activo de 30 días','Análisis avanzado de reputación','Reportes e historial de recomendaciones']}
];
export default function Home(){
 return <main className="refLanding">
  <header className="refNav"><a className="refBrand" href="/" aria-label="Nival inicio"><b>N</b><span>NIVAL</span></a><nav aria-label="Navegación principal"><a href="#como">Cómo funciona</a><a href="#precios">Precios</a><a href="#preguntas">Preguntas</a><a href="/demo">Ver demo</a></nav><a className="refRegister" href="/acceso?modo=registro">Crear cuenta <LandingIcon name="arrow"/></a><LandingInteractions mode="menu" wa={wa}/></header>
  <section className="refHero"><div className="refHeroText"><h1>Que te<br/>encuentren.<br/><span className="refHeroReturn">Que vuelvan.</span></h1><p>Puntos digitales y reseñas para<br className="refDesktop"/> hacer crecer tu negocio.</p><div className="refHeroActions"><a href="/acceso?modo=registro" className="refPrimary">Crear cuenta <LandingIcon name="arrow"/></a><a href="/demo" className="refOutline">Ver demo</a></div><div className="refQuick"><span><LandingIcon name="phone"/>Sin app</span><span><LandingIcon name="qr"/>QR incluido</span><span><LandingIcon name="card"/>Tarjetas digitales</span></div></div><div className="refHeroPhoto"><ReferenceImage file="hero-phone.webp" width={1400} height={1200} alt="Tarjeta de lealtad Café Nival en un teléfono dentro de una cafetería"/></div></section>
  <section className="refHow" id="como"><div className="refHowTop"><div><span className="refEyebrow">CÓMO FUNCIONA</span><h2>En 4 pasos,<br/>más clientes<br/>para tu negocio.</h2></div><LandingInteractions mode="arrows"/></div><div className="refSteps" id="refSteps">{[
    ['01.','Te encuentran en Google.','Mejora tu ficha y atrae más clientes cerca de ti.'],
    ['02.','Acumulan puntos.','Cada visita con compra suma un punto en su tarjeta digital.'],
    ['03.','Regresan por sus premios.','A todos nos gusta completar una meta.'],
    ['04.','Comparten su experiencia.','Puedes pedirles una reseña de forma amable y libre.']
  ].map(([num,title,description],i)=><article className="refStep" key={num}><strong>{num}</strong><h3>{title}</h3><p>{description}</p><ReferenceImage file={["google-phone.webp","step-02.webp","step-03.webp","barista.webp"][i]} width={600} height={900} alt={title}/></article>)}</div></section>
  <section className="refGoogle"><div className="refInfo"><span className="refEyebrow">TU NEGOCIO, EN TODAS PARTES</span><h2>Una buena ficha de Google<br/>atrae nuevos clientes.</h2><ul><li><i><LandingIcon name="search"/></i>Apareces en búsquedas locales</li><li><i><LandingIcon name="star"/></i>Más reseñas y mejor reputación</li><li><i><LandingIcon name="people"/></i>Más personas cerca de tu negocio</li><li><i><LandingIcon name="trend"/></i>Destacas frente a tu competencia</li></ul></div><div className="refGooglePhoto"><ReferenceImage file="cafe-front.webp" width={1200} height={1000} alt="Fachada de cafetería Nival"/><div className="refNearby"><span><LandingIcon name="pin"/></span> + Clientes cerca<br/> de tu negocio</div><ReferenceImage className="refGooglePhone" file="google-phone.webp" width={600} height={900} alt="Ficha ilustrativa de Café Nival en Google"/></div></section>
  <section className="refCustomers"><div className="refCustomersPhoto"><ReferenceImage file="barista.webp" width={1200} height={900} alt="Barista con tableta en cafetería"/><div className="refMetrics"><div><small>Nuevos clientes</small><b>+24</b><svg viewBox="0 0 70 28" aria-hidden="true">{[7,12,10,19,16,24,22].map((h,i)=><rect key={i} x={i*10} y={28-h} width="6" height={h} fill="#71a7ea"/>)}</svg><small>esta semana</small></div><div><small>Visitas totales</small><b>482</b><svg viewBox="0 0 70 28" aria-hidden="true"><polyline points="0,24 12,20 23,22 35,10 47,13 59,4 70,2" fill="none" stroke="#268a5b" strokeWidth="2"/></svg><small>+18%</small></div><div><small>Premios canjeados</small><b>36</b><svg viewBox="0 0 70 28" aria-hidden="true">{[9,17,12,23,18,26,20].map((h,i)=><rect key={i} x={i*10} y={28-h} width="6" height={h} fill="#4e9b57"/>)}</svg><small>+12%</small></div></div></div><div className="refInfo"><span className="refEyebrow">CONOCE A TUS CLIENTES</span><h2>Haz que cada<br/>visita cuente.</h2><ul><li><i><LandingIcon name="people"/></i>Más clientes habituales</li><li><i><LandingIcon name="gift"/></i>Premios que realmente funcionan</li><li><i><LandingIcon name="chart"/></i>Conoce qué los hace volver</li><li><i><LandingIcon name="trend"/></i>Promociones para atraerlos de regreso</li></ul></div></section>
  <section className="refValue"><div className="refValueIntro"><span className="refEyebrow">MÁS QUE PUNTOS. UNA RAZÓN PARA VOLVER.</span><h2>Convierte visitas sueltas<br/>en una comunidad fiel.</h2><p>Nival conecta tu presencia en Google con una tarjeta digital fácil de usar. Tú atiendes mejor; cada cliente tiene un motivo para regresar.</p></div><div className="refValueCanvas"><div className="refValueLead"><span className="refValueSpark">✳</span><small>EL VALOR PARA TU NEGOCIO</small><strong>Crece visita<br/>a visita.</strong><span>Una experiencia completa, desde que te descubren hasta que vuelven.</span></div><div className="refValueTags"><span className="valueTag tagLime"><b>+</b> clientes frecuentes</span><span className="valueTag tagWhite"><b>↗</b> más visitas recurrentes</span><span className="valueTag tagCoral"><b>★</b> confianza y reseñas</span><span className="valueTag tagWhite"><b>◎</b> una ficha que destaca</span><span className="valueTag tagGreen"><b>✦</b> clientes reconocidos</span><span className="valueTag tagLime"><b>↗</b> mejor relación con tus clientes</span><span className="valueTag tagWhite"><b>+</b> nuevas oportunidades de venta</span><span className="valueTag tagCoral"><b>◎</b> un programa sin app</span></div></div></section>
  <section className="refPricing" id="precios"><div className="refPricingHead"><div><span className="refEyebrow">PLANES NIVAL</span><h2>Encuentra el plan ideal<br/>para tu negocio.</h2></div></div><div className="refPlans">{plans.map(plan=><article className={plan.popular?'refPlan popular':'refPlan'} key={plan.name}>{plan.popular&&<div className="refPopular">Más popular</div>}<h3>{plan.name}</h3><p className="refPrice">${plan.price}<small> MXN / mes</small></p><ul>{plan.features.map(f=><li key={f}><Check/>{f}</li>)}</ul><a href="/acceso?modo=registro" className={plan.popular?'refPrimary':'refOutline'}>Crear cuenta <LandingIcon name="arrow"/></a></article>)}</div><div className="refBenefits"><span className="refEyebrow">¿POR QUÉ TENER UN SISTEMA DE PUNTOS + UNA<br/> BUENA FICHA DE GOOGLE?</span><div className="refBenefitContainer"><LandingInteractions mode="benefits" items={features}/></div></div></section>

  <section className="refFaq" id="preguntas"><div className="refFaqIntro"><span className="refEyebrow">PREGUNTAS FRECUENTES</span><h2>Todo claro desde<br/>la primera visita.</h2><p>Conoce lo esencial antes de empezar con Nival.</p></div><div className="refFaqList"><details><summary>¿Mis clientes necesitan descargar una app?</summary><p>No. Acceden a su tarjeta digital desde un enlace o QR, sin instalar una aplicación.</p></details><details><summary>¿Cómo se registran los puntos?</summary><p>Tu equipo registra la visita desde el flujo de negocio y los puntos se reflejan en la tarjeta del cliente.</p></details><details><summary>¿Puedo elegir los premios?</summary><p>Sí. Configuras recompensas que tengan sentido para tu negocio y tu comunidad.</p></details><details><summary>¿Nival cambia o responde reseñas en mi nombre?</summary><p>En Plus, el equipo de Nival prepara y publica manualmente hasta 100 respuestas personalizadas por cada periodo de 30 días. Por ahora, cada respuesta se revisa y publica desde Google; no se envían automáticamente.</p></details><details><summary>¿Qué plan me conviene?</summary><p>Nival Puntos te ayuda a premiar visitas. Esencial suma diagnóstico y seguimiento de reseñas. Plus agrega hasta 100 respuestas personalizadas cada 30 días, resumen de opiniones, áreas de mejora y analítica avanzada.</p></details><details><summary>¿Cómo empiezo?</summary><p>Crea tu cuenta o escríbenos y te orientamos para configurar tu negocio.</p></details></div></section>
  <section className="refContact" id="contacto"><div><span className="refEyebrow">HABLEMOS DE TU NEGOCIO</span><h2>Tu próxima visita<br/>puede empezar hoy.</h2><p>Cuéntanos qué quieres hacer crecer. Te ayudamos a encontrar el mejor punto de partida.</p><a href="tel:+525539044988" className="refContactPhone"><span>LLÁMANOS</span><strong>55 3904 4988</strong></a></div><div className="refContactAction"><span className="refContactIcon"><LandingIcon name="phone"/></span><strong>¿Listo para que tus clientes vuelvan?</strong><p>Da el primer paso para crear una experiencia que invite a regresar.</p><a href="tel:+525539044988" className="refPrimary">Contactar a Nival <LandingIcon name="arrow"/></a><a href="#precios" className="refContactText">Ver planes y precios</a></div></section>
  <footer className="refFooter"><a className="refBrand" href="/" aria-label="Nival inicio"><b>N</b><span>NIVAL</span></a><p>Para negocios locales en México.</p><nav aria-label="Enlaces del pie"><a href="/terminos">Términos</a><a href="/privacidad">Aviso de privacidad</a><a href="/acceso">Acceso a negocios</a><a href="/staff/acceso">Acceso de personal</a><a href="/acceso-administrador">Acceso de administradores</a></nav><small>© 2026 Nival Tech · México</small></footer>
  <WhatsAppFab href={wa}/>
 </main>
}