import {requireRole,requireBusiness} from '../../../lib/foundation/session';
import {query} from '../../../lib/foundation/db';
import {ReportView} from '../../../lib/reputation/report-view';
export const dynamic='force-dynamic';
export default async function Reports({searchParams}:{searchParams:Promise<{business?:string}>}){
 const actor=await requireRole('owner'),params=await searchParams;const businesses=await query(actor,'select b.id,b.name,p.features from nival_pr.businesses b left join nival_pr.plans p on p.id=b.plan_id order by b.name');
 const b=params.business?businesses.find(b=>b.id===params.business):businesses[0];if(!b)return <main className="dashboard"><a href="/panel">Volver al panel</a><p>Negocio no encontrado.</p></main>;
 await requireBusiness(actor,b.id);if(b.features?.points_only===true)return <main className="dashboard"><header className="dashHead"><h1>Reportes de {b.name}</h1><a href={'/panel?business='+b.id}>Volver a mi panel</a></header><section className="reviewBox"><h2>Este plan incluye solo puntos</h2><p>Los reportes de reseñas y reputación se incluyen en los planes Nival Esencial y Plus.</p><a href="https://wa.me/525539044788?text=Hola%2C%20quiero%20agregar%20rese%C3%B1as%20a%20mi%20plan%20Nival" target="_blank" rel="noreferrer">Preguntar por un plan con reseñas</a></section></main>;const reports=await query(actor,"select r.*,b.name business_name,to_char(r.period_start,'YYYY-MM-DD') period_start,to_char(r.period_end,'YYYY-MM-DD') period_end from nival_pr.generated_reports r join nival_pr.businesses b on b.id=r.business_id where r.business_id=$1 and r.status='approved' order by r.created_at desc limit 40",[b.id]);
 return <main className="dashboard"><header className="dashHead"><h1>Reportes de {b.name}</h1><a href={'/panel?business='+b.id}>Volver a mi panel</a></header>{reports.map(r=><ReportView key={r.id} report={r}/>)}{!reports.length&&<p>Tu diagnóstico y próximos reportes aparecerán aquí cuando Nival los revise y publique.</p>}</main>;
}
