import {cookies} from 'next/headers';
import {notFound} from 'next/navigation';
import {query,authScope,foundationEnabled} from '../../../lib/foundation/db';
import {sha256} from '../../../lib/foundation/security.mjs';
import {enroll,consentCard,chooseGoal} from '../../../lib/foundation/actions';
import {ActionForm} from '../../../lib/foundation/forms';
import {Field,Hidden} from '../../../lib/foundation/fields';
export const dynamic='force-dynamic';
export default async function Customer({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;if(!foundationEnabled())return <main className="dashboard"><h1>Programa en preparación</h1><a href="/demo">Ver demostración</a></main>;
 const [row]=await query(authScope(),'select nival_pr_private.public_business($1) as data',[slug]);if(!row?.data)notFound();const b=row.data;
 const token=(await cookies()).get('nival_customer_'+b.id)?.value;
 const hash=token&&/^[A-Za-z0-9_-]{43}$/.test(token)?sha256(token):null;
 const [customer]=hash?await query({role:'customer',tokenHash:hash},'select id from nival_pr.customers where business_id=$1',[b.id]):[];
 const [valid]=hash&&!customer?await query(authScope(),'select nival_pr_private.customer_token_valid($1,$2) as valid',[b.id,hash]):[];
 const [balance]=customer&&hash?await query({role:'customer',tokenHash:hash},'select nival_pr.point_balance($1) as points',[customer.id]):[];
 const googleUrl=typeof b.google_maps_url==='string'&&/^https:\/\/(?:g\.page|maps\.app\.goo\.gl|(?:www\.)?google\.com)\//.test(b.google_maps_url)?b.google_maps_url:null;
 return <main className="dashboard publicReview pointCard"><header><small>NIVAL · LEALTAD</small><h1>{b.name}</h1><p>{b.program?.name||'Tus recompensas'}</p></header>{!b.active?<section className="reviewBox"><h2>Programa no disponible</h2><p>Consulta al negocio para conocer la disponibilidad del servicio.</p></section>:customer?<section className="reviewBox"><h2>Tu tarjeta</h2><p className="pointBalance">{String(balance?.points||0)} <span>puntos disponibles</span></p><p>El personal suma tus puntos después de tu visita.</p></section>:valid?.valid?<section className="reviewBox"><h2>Activa tu tarjeta</h2><ActionForm action={consentCard} label="Consultar mis puntos"><Hidden name="slug" value={slug}/><label className="wide"><input name="consent" type="checkbox" required/>Acepto que {b.name} registre mi nombre, teléfono y visitas para administrar este programa de lealtad. Puedo solicitar la baja directamente al negocio.</label></ActionForm></section>:<section className="reviewBox"><h2>Obtén tu tarjeta</h2><p>Sin descargar aplicaciones. Tu tarjeta quedará vinculada a este navegador.</p><ActionForm action={enroll} label="Crear mi tarjeta"><Hidden name="slug" value={slug}/><Field name="name" label="Tu nombre"/><Field name="phone" label="Teléfono" type="tel"/><label className="wide"><input type="checkbox" name="consent" required/>Acepto que {b.name} registre mi nombre, teléfono y visitas para administrar este programa de lealtad. Puedo solicitar la baja directamente al negocio.</label></ActionForm></section>}{customer&&b.active&&b.program?.mode==='choose'&&<section className="reviewBox"><h2>Elige tu meta</h2><ActionForm action={chooseGoal} label="Elegir este premio"><Hidden name="slug" value={slug}/><label>Premio<select name="rewardId">{(b.rewards||[]).map((r:any)=><option key={r.id} value={r.id}>{r.name} · {r.points_cost} puntos</option>)}</select></label></ActionForm></section>}<section className="reviewBox"><h2>Recompensas</h2>{(b.rewards||[]).map((r:any)=><p key={r.id}><strong>{r.name}</strong> · {r.points_cost} puntos</p>)}{!b.rewards?.length&&<p>El negocio está preparando sus premios.</p>}</section>{googleUrl&&<p><a className="reviewCta" href={googleUrl} target="_blank" rel="noopener noreferrer">Dejar una reseña en Google</a></p>}<p className="notice">Si cambias de teléfono o borras las cookies, pide al negocio un nuevo acceso. Tu saldo no se borra.</p></main>;
}
