'use client';
import {useState} from 'react';
import {filterCustomers,customerCsv} from './explorer.mjs';
import {Icon} from './icons';
export function CustomerExplorer({customers,demo=false,fixedSegment}:{customers:Record<string,any>[];demo?:boolean;fixedSegment?:string}){
 const [search,setSearch]=useState(''),[segment,setSegment]=useState(fixedSegment||'all'),[sort,setSort]=useState('visits'),[page,setPage]=useState(1);
 const shown=filterCustomers(customers,search,segment,sort);
 const pages=Math.max(1,Math.ceil(shown.length/20)),currentPage=Math.min(page,pages);
 function download(){const url=URL.createObjectURL(new Blob([customerCsv(shown)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=demo?'clientes-demo.csv':'clientes-nival.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <article className="ownerCard customerExplorer"><div className="workspaceCardHead"><div><span className="workspaceEyebrow">DIRECTORIO DE CLIENTES</span><h3>Conoce a las personas que vuelven</h3></div><button type="button" className="workspaceSecondary" onClick={download} disabled={!shown.length}><Icon name="download" size={16}/> Exportar CSV</button></div><div className="explorerFilters"><label className="explorerSearch"><span>Buscar cliente</span><div><Icon name="search" size={18}/><input type="search" placeholder="Escribe un nombre…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div></label>{!fixedSegment&&<label>Tipo de cliente<select value={segment} onChange={e=>{setSegment(e.target.value);setPage(1);}}><option value="all">Todos los clientes</option><option value="new">Nuevos</option><option value="frequent">Frecuentes</option><option value="risk">En riesgo</option><option value="lost">Perdidos</option><option value="absent">Sin visita este mes</option></select></label>}<label>Ordenar por<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="visits">Más visitas</option><option value="recent">Visita más reciente</option><option value="name">Nombre A–Z</option></select></label></div><p className="explorerCount" role="status">{shown.length} de {customers.length} clientes {search||segment!=='all'?'coinciden con tu búsqueda':''}</p><div className="customerTableWrap"><table className="customerTable"><thead><tr><th scope="col">Cliente</th><th scope="col">Visitas</th><th scope="col">Última visita</th><th scope="col">Relación</th></tr></thead><tbody>{shown.slice((currentPage-1)*20,currentPage*20).map(c=><tr key={c.id}><td><span className="tableAvatar">{String(c.name).slice(0,1).toUpperCase()}</span><strong>{c.name}</strong></td><td data-label="Visitas"><b>{Number(c.visits||0)}</b></td><td data-label="Última visita">{c.last_visit?new Date(c.last_visit).toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric',timeZone:'America/Mexico_City'}):'Aún sin visitas'}</td><td data-label="Relación"><span className={'customerBadge '+(c.is_lost||c.is_risk?'needsCare':'')}>{c.is_lost?'Por recuperar':c.is_risk?'En riesgo':c.is_frequent?'Frecuente':c.is_new?'Nuevo':'En seguimiento'}</span></td></tr>)}</tbody></table></div>{!shown.length&&<p className="ownerEmpty">No encontramos clientes con estos filtros. Prueba otro nombre o selecciona “Todos los clientes”.</p>}<nav className="customerPagination" aria-label="Páginas de clientes"><button type="button" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Anterior</button><span role="status">Página {currentPage} de {pages} · hasta 20 clientes por página</span><button type="button" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Siguiente</button></nav><small className="explorerPrivacy">El archivo incluye solo los clientes del filtro actual. Los teléfonos no se incluyen en la exportación.</small></article>;
}
