import {quoteUrl} from "../foundation/registration.mjs";
import {RegistrationFields} from "../foundation/registration-fields";
import {logout,registerBusiness} from '../foundation/actions';
import {redeemActivationCode} from '../admin/actions';
import {ActionForm} from '../foundation/forms';
import {Field,Hidden} from '../foundation/fields';
import {checklistLabels,periodRange} from './domain.mjs';
import {Bars,RatingLine} from './charts';
import {SegmentCard,PeriodFilter} from './clients';
import {saveSegments} from './actions';
const number=(v:number)=>Number(v||0).toLocaleString('es-MX');
function Metric({label,value,previous}:{label:string;value:number|string;previous?:number}){return <article className="ownerCard ownerMetric"><span>{label}</span><strong>{typeof value==='number'?number(value):value}</strong>{previous!==undefined&&<small>{Number(value)-previous>0?'+':''}{number(Number(value)-previous)} respecto al anterior · {number(previous)} antes</small>}</article>;}
export function OwnerView({actor,b,businesses,range,data,demo=false}:{actor:Record<string,any>;b:Record<string,any>;businesses:Record<string,any>[];range:ReturnType<typeof periodRange>;data:Record<string,any>;demo?:boolean}){
 const current=data.metrics.find((x:Record<string,any>)=>x.period==='current')!,prev=data.metrics.find((x:Record<string,any>)=>x.period==='previous')!;
 const settings=data.settings||{new_days:14,frequent_days:30,frequent_visits:3,risk_from:31,lost_after:60,risk_visits:2};
 const segments=[['new','Nuevos',`Primera visita en los últimos ${settings.new_days} días`,'is_new'],['frequent','Frecuentes',`${settings.frequent_visits}+ visitas en los últimos ${settings.frequent_days} días`,'is_frequent'],['risk','En riesgo',`${settings.risk_from}–${settings.lost_after} días sin venir y ${settings.risk_visits}+ visitas`,'is_risk'],['lost','Perdidos',`Más de ${settings.lost_after} días sin visitar`,'is_lost'],['absent','No han venido este mes','Incluye tarjetas que aún no tienen una visita','absent_month']];
 const last=data.last,distribution=last?.distribution||{},hasDistribution=[1,2,3,4,5].reduce((s,n)=>s+Number(distribution[n]||0),0)===Number(last?.total_reviews)&&Object.keys(distribution).length>0;
 const quote=quoteUrl(b);
 const active=b.status==='activo'&&(new Date(b.paid_until||0).getTime()>Date.now()||new Date(b.trial_ends_at||0).getTime()>Date.now());
 return <main className="ownerDashboard">{demo&&<aside className="ownerDemo">Demostración de solo lectura · 20 clientes ficticios · corte al 5 de octubre de 2026. <a href="/acceso">Entrar a mi negocio</a></aside>}<header className="ownerHeader"><div><small>NIVAL · MI NEGOCIO</small><h1>{b.name}</h1><p>Hola, {actor.name}</p></div>{!demo&&<form action={logout}><button>Cerrar sesión</button></form>}</header>
 {!demo&&<div className="ownerTools">{businesses.length>1&&<nav aria-label="Tus negocios">{businesses.map((x:Record<string,any>)=><a key={x.id} href={'/panel?business='+x.id} aria-current={x.id===b.id?'page':undefined}>{x.name}</a>)}</nav>}<a href={'/panel/puntos?business='+b.id}>Configurar puntos y meseros ↗</a><a href={'/b/'+b.slug}>Tarjeta del cliente ↗</a></div>}
 {!demo&&!active&&<section className="ownerCard accountLock"><h2>Activa o renueva tu servicio</h2><p>Tu historial permanece disponible. Renueva para registrar nuevas visitas.</p><a href={quote} target="_blank" rel="noreferrer">Cotizar o activar por WhatsApp</a><ActionForm action={redeemActivationCode} label="Activar con código"><Hidden name="businessId" value={b.id}/><Field name="code" label="Código NIV-XXXX-XXXX"/></ActionForm></section>}
 <nav className="ownerTabs" aria-label="Bloques del panel"><a href="#resumen">Resumen</a><a href="#google">Google</a><a href="#clientes">Clientes</a></nav>
 <PeriodFilter demo={demo} businessId={b.id} kind={range.kind} value={range.key}/><p className="periodCaption">{range.start} a {range.end} (fin excluido) · Ciudad de México. Comparativo: {range.previous} a {range.start}.</p>
 <section id="resumen" className="ownerBlock"><div className="ownerSectionTitle"><small>EL PULSO DE TU NEGOCIO</small><h2>Resumen</h2></div><div className="ownerMetrics">
 {([['Visitas','visits'],['Clientes nuevos','new_customers'],['Puntos otorgados','points'],['Premios canjeados','redeemed'],['Canjes pendientes del periodo','pending']] as const).map(([label,key])=><Metric key={key} label={label} value={current[key]} previous={prev[key]}/>)}</div>
 {!current.visits&&<p className="ownerEmpty">Aún no hay visitas en este periodo. Comparte el QR del negocio y registra cada visita desde el escáner del mesero.</p>}
 <article className="ownerCard"><h3>Actividad de meseros</h3><p className="cardCaption">Señales para revisar; no prueban fraude. Volumen alto: al menos 10 visitas y más del doble del promedio de los demás operadores.</p>{!data.ranking.length?<p className="ownerEmpty">El ranking aparecerá con el primer movimiento.</p>:<ol className="staffRanking">{data.ranking.map((r:Record<string,any>)=>{const others=data.ranking.filter((x:Record<string,any>)=>x.staff_id!==r.staff_id),avg=others.length?others.reduce((s:number,x:Record<string,any>)=>s+x.visits,0)/others.length:0;const high=others.length>0&&r.visits>=10&&r.visits>avg*2;return <li key={r.staff_id}><b>{r.name}</b><span>{r.visits} visitas · {r.redemptions} canjes · {r.customers} clientes</span>{high&&<small className="ownerAlert">Revisar: volumen de visitas alto.</small>}{r.reversed>0&&<small className="ownerAlert">Revisar: {r.reversed} canjes revertidos.</small>}{r.pending>0&&<small>{r.pending} canjes pendientes de revisión.</small>}</li>;})}</ol>}</article></section>
 <section id="google" className="ownerBlock"><div className="ownerSectionTitle"><small>DATOS CARGADOS POR NIVAL</small><h2>Google</h2></div>
 {last?<><p className="cardCaption">Ficha al cierre del último reporte disponible: {String(last.period).slice(0,10)} · {last.period_kind==='day'?'diario':last.period_kind==='year'?'anual':'mensual'}.</p><div className="ownerMetrics"><Metric label="Calificación al cierre" value={String(last.rating)+' ★'}/><Metric label="Reseñas totales" value={Number(last.total_reviews)}/><Metric label="Nuevas del periodo" value={data.google?data.google.fresh:'—'}/><Metric label="Respondidas del periodo" value={data.google?.answered!==null&&data.google?data.google.answered:'—'}/><Metric label="Pendientes del periodo" value={data.google?.answered!==null&&data.google?Math.max(0,data.google.fresh-data.google.answered):'—'}/><Metric label="Respuesta del periodo" value={data.google?.answered!==null&&data.google?(data.google.fresh?Math.round(data.google.answered/data.google.fresh*100)+'%':'—'):'—'}/></div>
 {data.google&&data.google.answered===null&&<p className="ownerEmpty">Este reporte histórico no separa respuestas del periodo. Nival debe actualizarlo desde admin para mostrar pendientes y porcentaje.</p>}
 {!data.google&&<p className="ownerEmpty">No hay reporte para este filtro. Un reporte mensual no se divide en cifras diarias: elige el mes o espera la carga del día.</p>}
 {data.google&&<p className="cardCaption">Cifras de nuevas y respuestas basadas en reportes {data.google.resolution==='day'?'diarios':data.google.resolution==='year'?'anuales':'mensuales'}. La ficha y su distribución son una fotografía al cierre, no una suma de totales.</p>}
 <div className="ownerChartGrid">{hasDistribution?<><Bars title="Distribución por estrellas" items={[5,4,3,2,1].map(n=>({label:n+' ★',value:Number(distribution[n]||0),color:'#175d47'}))}/><Bars title="Sentimiento de las reseñas" items={[{label:'Positivas · 4–5',value:Number(distribution[4]||0)+Number(distribution[5]||0),color:'#175d47'},{label:'Neutras · 3',value:Number(distribution[3]||0),color:'#b98832'},{label:'Negativas · 1–2',value:Number(distribution[1]||0)+Number(distribution[2]||0),color:'#ba5850'}]}/></>:<p className="ownerEmpty">Nival todavía debe cargar una distribución por estrellas que coincida con el total.</p>}<RatingLine reports={data.reports}/></div>
 <div className="ownerChartGrid"><article className="ownerCard"><h3>Áreas de mejora de la ficha</h3><ul className="profileChecklist">{Object.entries(checklistLabels).map(([k,label])=><li key={k}><span>{label}</span><b className={last.profile_checklist[k]?'checkDone':'checkPending'}>{last.profile_checklist[k]?'✓ Revisado':'Pendiente'}</b></li>)}</ul></article><article className="ownerCard"><h3>Consejos de Nival</h3><p className="preserveLines">{last.notes||'Nival aún no ha agregado consejos a este reporte.'}</p></article></div></>:<p className="ownerEmpty">Tu primer reporte está pendiente. Comparte con Nival el enlace de tu ficha de Google para iniciar la revisión; aquí verás las métricas cuando se carguen.</p>}
 <article className="ownerCard"><h3>Cambios realizados por Nival</h3>{data.changes.length?<ul className="ownerChangelog">{data.changes.map((c:Record<string,any>)=><li key={c.id}><time>{new Date(c.date).toLocaleDateString('es-MX',{timeZone:'America/Mexico_City'})}</time><p className="preserveLines">{c.description}</p></li>)}</ul>:<p className="ownerEmpty">No se registraron cambios en este periodo.</p>}</article></section>
 <section id="clientes" className="ownerBlock"><div className="ownerSectionTitle"><small>RELACIONES QUE IMPORTAN</small><h2>Clientes</h2><p>Segmentos al {range.today}. Un cliente puede estar en más de uno. Solo se cuentan visitas; canjes y ajustes no agregan visitas.</p></div><div className="ownerSegmentGrid">{segments.map(([key,title,description,flag])=><SegmentCard key={key} segment={key} title={title} description={description} customers={data.segments.filter((c:Record<string,any>)=>c[flag])} templates={data.templates as {segment:string;text:string}[]} businessName={b.name} demo={demo}/>)}</div>
 {!demo&&<details className="ownerCard"><summary>Configurar umbrales de clientes</summary><ActionForm action={saveSegments} label="Guardar umbrales"><Hidden name="businessId" value={b.id}/>{[['new_days','Días para nuevos',365],['frequent_days','Ventana de frecuentes (días)',365],['frequent_visits','Visitas mínimas para frecuentes',100],['risk_from','Días sin venir: inicio de riesgo',730],['lost_after','Días sin venir: fin de riesgo',731],['risk_visits','Visitas mínimas previas para riesgo',100]].map(([name,label,max])=><Field key={name} name={String(name)} label={String(label)} type="number" min={name==='lost_after'?2:1} max={Number(max)} value={settings[String(name)]}/>)}</ActionForm></details>}</section>
 {!demo&&<details className="ownerCard"><summary>Registrar otro negocio</summary><ActionForm action={registerBusiness}><RegistrationFields/></ActionForm></details>}
 </main>;
}
