import {PlanChoices} from './plan-choices';
import {AccountState} from './account-state';
import {entitlements} from '../foundation/entitlements.mjs';
import {ReviewInsights} from './review-insights';
import {DashboardShell} from './shell';
import {CustomerExplorer} from './customer-explorer';
import {ShareTools} from './share-tools';
import {Icon} from './icons';
import {quoteUrl} from "../foundation/registration.mjs";
import {RegistrationFields} from "../foundation/registration-fields";
import {logout,registerBusiness} from '../foundation/actions';
import {redeemActivationCode} from '../admin/actions';
import {ActionForm} from '../foundation/forms';
import {Field,Hidden} from '../foundation/fields';
import {checklistLabels,periodRange,inclusivePeriodEnd,formatPeriodDate} from './domain.mjs';
import {Bars,RatingLine} from './charts';
import {SegmentCard,PeriodFilter} from './clients';
import {defaultMessages} from './messages.mjs';
import {saveMessageTemplate} from './actions';
import {saveSegments} from './actions';
const number=(v:number)=>Number(v||0).toLocaleString('es-MX');
function Metric({label,value,previous}:{label:string;value:number|string;previous?:number}){return <article className="ownerCard ownerMetric"><span>{label}</span><strong>{typeof value==='number'?number(value):value}</strong>{previous!==undefined&&<small>{Number(value)-previous>0?'+':''}{number(Number(value)-previous)} respecto al anterior · {number(previous)} antes</small>}</article>;}
function RetentionMetric({current,previous}:{current:Record<string,any>;previous:Record<string,any>}){const rate=current.active_customers?Math.round(Number(current.returning_customers||0)/Number(current.active_customers)*100):0;const before=previous.active_customers?Math.round(Number(previous.returning_customers||0)/Number(previous.active_customers)*100):0;return <article className="ownerCard ownerMetric"><span>Retención de clientes</span><strong>{rate}%</strong><small>{rate-before>0?'+':''}{rate-before} pp. frente al periodo anterior · {before}% antes</small><small>Clientes activos que ya habían visitado</small></article>;}
export function OwnerView({actor,b,businesses,range,data,demo=false,mobilePreview=false}:{actor:Record<string,any>;b:Record<string,any>;businesses:Record<string,any>[];range:ReturnType<typeof periodRange>;data:Record<string,any>;demo?:boolean;mobilePreview?:boolean}){
 const pointsOnly=b.features?.points_only===true;
 const current=data.metrics.find((x:Record<string,any>)=>x.period==='current')!,prev=data.metrics.find((x:Record<string,any>)=>x.period==='previous')!;
 const settings=data.settings||{new_days:14,frequent_days:30,frequent_visits:3,risk_from:31,lost_after:60,risk_visits:2};
 const segments=[['new','Nuevos',`Primera visita en los últimos ${settings.new_days} días`,'is_new'],['frequent','Frecuentes',`${settings.frequent_visits}+ visitas en los últimos ${settings.frequent_days} días`,'is_frequent'],['risk','En riesgo',`${settings.risk_from}–${settings.lost_after} días sin venir y ${settings.risk_visits}+ visitas`,'is_risk'],['lost','Perdidos',`Más de ${settings.lost_after} días sin visitar`,'is_lost'],['absent','No han venido este mes','Incluye tarjetas que aún no tienen una visita','absent_month']];
 const last=data.last,distribution=last?.distribution||{},hasDistribution=[1,2,3,4,5].reduce((s,n)=>s+Number(distribution[n]||0),0)===Number(last?.total_reviews)&&Object.keys(distribution).length>0;
 const quote=quoteUrl(b);
 const access=entitlements(b);
 const active=access.active;
 const risk=data.segments.filter((c:Record<string,any>)=>c.is_risk||c.is_lost).length;
 const atRisk=data.segments.filter((c:Record<string,any>)=>c.is_risk&&!c.is_lost).length;
 const returners=data.segments.filter((c:Record<string,any>)=>c.is_frequent).length;
 const inactive=data.segments.filter((c:Record<string,any>)=>c.is_lost).length;
 const pendingReviews=data.google&&data.google.answered!==null?Math.max(0,Number(data.google.fresh)-Number(data.google.answered)):null;
 const visitChange=prev.visits?Math.round((current.visits-prev.visits)/prev.visits*100):null;
 const status=active||demo?'Activo':b.status==='pausado'?'Pausado':'Por activar';
 if(!demo&&!active&&!data.segments.length&&!data.last)return <DashboardShell name={b.name} owner={actor.name} status={status} demo={false} logout={<form action={logout}><button>Cerrar sesión</button></form>}><AccountState b={b}/></DashboardShell>;
 return <DashboardShell pointsOnly={pointsOnly} name={b.name} owner={actor.name} status={status} demo={demo} mobilePreview={mobilePreview} logout={<form action={logout}><button className="logoutButton" aria-label="Cerrar sesión" title="Cerrar sesión"><Icon name="logout" size={18}/></button></form>}><main className="ownerDashboard">
 {!demo&&!active&&<AccountState b={b}/>}
 <div className="workspacePeriod"><div><Icon name="clock" size={18}/><span>Periodo de tus resultados</span></div>
 <PeriodFilter demo={demo} businessId={b.id} kind={range.kind} value={range.key}/></div><p className="periodCaption">Del {formatPeriodDate(range.start)} al {formatPeriodDate(inclusivePeriodEnd(range.end))} · Hora de Ciudad de México · Comparado con el periodo anterior.</p>
 <section id="resumen" data-panel="inicio" className="ownerBlock"><div className="workspaceHero"><div><span className="heroKicker"><span/> TU NEGOCIO, CONECTADO</span><h2>Resumen de tu negocio</h2><p>Hola, {actor.name.split(' ')[0]}. Este es el pulso de {b.name} en el periodo seleccionado.</p><div className="workspaceActionRow"><a href="#clientes" className="workspacePrimary">Ver mis clientes <Icon name="arrow" size={16}/></a>{!demo&&<a href={"/panel/reportes?business="+b.id} className="heroTextLink">Mis reportes y recomendaciones</a>}<a href="#compartir" className="heroTextLink">Compartir mi tarjeta <Icon name="compartir" size={16}/></a></div></div><div className="heroSignal"><Icon name="clientes" size={28}/><strong>{number(data.segments.length)}</strong><span>clientes en tu comunidad</span><div><span/> {number(returners)} clientes frecuentes</div></div></div><div className="ownerSectionTitle"><small>EL PULSO DE TU NEGOCIO</small><h2>Resumen</h2></div><div className="ownerMetrics">
 {([['Visitas','visits'],['Clientes nuevos','new_customers'],['Puntos otorgados','points'],['Premios canjeados','redeemed'],['Canjes pendientes del periodo','pending']] as const).map(([label,key])=><Metric key={key} label={label} value={current[key]} previous={prev[key]}/>)}<RetentionMetric current={current} previous={prev}/></div>
 {!current.visits&&<p className="ownerEmpty">Aún no hay visitas en este periodo. Comparte el QR del negocio y registra cada visita desde el escáner del mesero.</p>}
 <div className="overviewBottom"><article className="ownerCard overviewComparison"><div className="workspaceCardHead"><div><span className="workspaceEyebrow">EVOLUCIÓN DEL NEGOCIO</span><h3>Visitas del periodo</h3></div><Icon name="trend"/></div><div className="comparisonHeadline"><strong>{number(current.visits)}</strong><span>{prev.visits>0?`${Math.round((current.visits-prev.visits)/prev.visits*100)>0?'+':''}${Math.round((current.visits-prev.visits)/prev.visits*100)}% vs. periodo anterior`:'Sin base anterior para comparar'}</span></div><Bars title="Comparación de visitas" unit="Visitas registradas en cada periodo" items={[{label:'Este periodo',value:Number(current.visits),color:'#226e57'},{label:'Anterior',value:Number(prev.visits),color:'#c4d5cc'}]}/></article><article className="ownerCard nextActions"><span className="workspaceEyebrow">TU SIGUIENTE PASO</span><h3>Pequeñas acciones. Más regresos.</h3><a href="#clientes-risk"><span className="actionIcon"><Icon name="clientes"/></span><span><strong>{risk?`${risk} clientes por recuperar`:'Construye una relación con tus clientes'}</strong><small>Revisa los segmentos y prepara un mensaje personal.</small></span><Icon name="arrow" size={16}/></a>{!pointsOnly&&<a href="#google"><span className="actionIcon"><Icon name="google"/></span><span><strong>{data.google?.answered!==null&&data.google?`${Math.max(0,data.google.fresh-data.google.answered)} reseñas pendientes del periodo`:'Consulta tu reputación en Google'}</strong><small>Revisa tus reportes y el trabajo realizado por Nival.</small></span><Icon name="arrow" size={16}/></a>}<a href="#compartir"><span className="actionIcon"><Icon name="compartir"/></span><span><strong>Haz visible tu programa de puntos</strong><small>Descarga el QR para tu mostrador.</small></span><Icon name="arrow" size={16}/></a></article></div>
 <div className="ownerSummarySignals" aria-label="Señales principales del negocio">
  <article className="ownerCard summarySignal"><span className="workspaceEyebrow">GOOGLE Y RESEÑAS</span><strong>{last?String(last.rating)+' ★':'Sin reporte'}</strong><p>{data.google?pendingReviews===null?`${number(data.google.fresh)} reseñas nuevas en el periodo; respuestas aún sin desglose.`:`${number(data.google.fresh)} nuevas · ${number(data.google.answered)} respondidas · ${number(pendingReviews)} pendientes.`:last?`${number(last.total_reviews)} reseñas en la última ficha revisada.`:pointsOnly?'Google no está incluido en tu plan actual.':'El primer reporte de Google está pendiente.'}</p><a href="#google">Ver Google <Icon name="arrow" size={15}/></a></article>
  <article className="ownerCard summarySignal"><span className="workspaceEyebrow">CLIENTES POR RECUPERAR</span><strong>{number(risk)}</strong><p>{number(inactive)} inactivos · {number(atRisk)} en riesgo · {number(returners)} frecuentes.</p><a href="#clientes-risk">Revisar clientes <Icon name="arrow" size={15}/></a></article>
  <article className="ownerCard summarySignal"><span className="workspaceEyebrow">ACTIVIDAD DEL PERIODO</span><strong>{number(current.visits)} visitas</strong><p>{number(current.new_customers)} clientes nuevos · {number(current.redeemed)} premios canjeados · comparación con el periodo anterior arriba.</p><a href="#clientes">Ver actividad de clientes <Icon name="arrow" size={15}/></a></article>
 </div>
 <div className="ownerSummaryAdvice">
  <article className="ownerCard"><span className="workspaceEyebrow">QUÉ VA BIEN</span><p>{current.visits>prev.visits?`Las visitas subieron ${visitChange}% frente al periodo anterior. Mantén el hábito de registrar cada compra.`:returners>0?`${number(returners)} clientes ya son frecuentes. Sigue reforzando la experiencia que los hace volver.`:current.visits>0?`Ya registraste ${number(current.visits)} visitas en este periodo; sigue midiendo cada semana.`:'Aún faltan datos suficientes para detectar qué está funcionando mejor.'}</p></article>
  <article className="ownerCard"><span className="workspaceEyebrow">QUÉ MEJORAR</span><p>{pendingReviews!==null&&pendingReviews>0?`Hay ${number(pendingReviews)} reseñas del periodo por responder. Revisa la sección Google.`:risk>0?`${number(risk)} clientes necesitan seguimiento. Empieza por quienes llevan más tiempo sin volver.`:!pointsOnly&&!last?'Pide a Nival que cargue el primer reporte de Google para detectar oportunidades de mejora.':current.visits<prev.visits?`Las visitas bajaron frente al periodo anterior. Comparte el QR y revisa la actividad de clientes.`:'Continúa registrando visitas y revisa el próximo periodo para detectar cambios.'}</p></article>
 </div></section>
 <section id="google" data-panel="google" className="ownerBlock"><div className="ownerSectionTitle"><small>DATOS CARGADOS POR NIVAL</small><h2>Google y reseñas</h2><p>Calificación, reseñas, respuestas, ficha de Google y recomendaciones reunidas en una sola vista.</p>{!demo&&<a className="workspaceTextLink" href={'/panel/reportes?business='+b.id}>Abrir reportes y recomendaciones</a>}{pointsOnly&&<p className="ownerEmpty">Historial conservado · Tu plan de $299 incluye puntos. Aquí puedes consultar los reportes anteriores; el seguimiento y los reportes nuevos se reactivan con $399 o $499.</p>}</div>{!demo&&!access.reviews&&<p className="ownerEmpty">Historial de reseñas en solo lectura. Los reportes anteriores se conservan; para nuevas respuestas y análisis, activa Esencial o Plus.</p>}
 {last?<><p className="cardCaption">Ficha al cierre del último reporte disponible: {String(last.period).slice(0,10)} · {last.period_kind==='day'?'diario':last.period_kind==='year'?'anual':'mensual'}.</p><div className="ownerMetrics"><Metric label="Calificación al cierre" value={String(last.rating)+' ★'}/><Metric label="Reseñas totales" value={Number(last.total_reviews)}/><Metric label="Nuevas del periodo" value={data.google?data.google.fresh:'—'}/><Metric label="Respondidas del periodo" value={data.google?.answered!==null&&data.google?data.google.answered:'—'}/><Metric label="Pendientes del periodo" value={data.google?.answered!==null&&data.google?Math.max(0,data.google.fresh-data.google.answered):'—'}/><Metric label="Respuesta del periodo" value={data.google?.answered!==null&&data.google?(data.google.fresh?Math.round(data.google.answered/data.google.fresh*100)+'%':'—'):'—'}/></div>
 {data.google&&data.google.answered===null&&<p className="ownerEmpty">Este reporte histórico no separa respuestas del periodo. Nival debe actualizarlo desde admin para mostrar pendientes y porcentaje.</p>}
 {!data.google&&<p className="ownerEmpty">No hay reporte para este filtro. Un reporte mensual no se divide en cifras diarias: elige el mes o espera la carga del día.</p>}
 {data.google&&<p className="cardCaption">Cifras de nuevas y respuestas basadas en reportes {data.google.resolution==='day'?'diarios':data.google.resolution==='year'?'anuales':'mensuales'}. La ficha y su distribución son una fotografía al cierre, no una suma de totales.</p>}
 <div className="ownerChartGrid">{hasDistribution?<><Bars title="Distribución por estrellas" items={[5,4,3,2,1].map(n=>({label:n+' ★',value:Number(distribution[n]||0),color:'#175d47'}))}/><Bars title="Sentimiento de las reseñas" items={[{label:'Positivas · 4–5',value:Number(distribution[4]||0)+Number(distribution[5]||0),color:'#175d47'},{label:'Neutras · 3',value:Number(distribution[3]||0),color:'#b98832'},{label:'Negativas · 1–2',value:Number(distribution[1]||0)+Number(distribution[2]||0),color:'#ba5850'}]}/></>:<p className="ownerEmpty">Nival todavía debe cargar una distribución por estrellas que coincida con el total.</p>}<RatingLine reports={data.reports}/></div>
 <div className="ownerChartGrid"><article className="ownerCard"><h3>Áreas de mejora de la ficha</h3><ul className="profileChecklist">{Object.entries(checklistLabels).map(([k,label])=><li key={k}><span>{label}</span><b className={last.profile_checklist[k]?'checkDone':'checkPending'}>{last.profile_checklist[k]?'✓ Revisado':'Pendiente'}</b></li>)}</ul></article></div><ReviewInsights notes={last.notes}/></>:<p className="ownerEmpty">Tu primer reporte está pendiente. Comparte con Nival el enlace de tu ficha de Google para iniciar la revisión; aquí verás las métricas cuando se carguen.</p>}
 <article className="ownerCard"><h3>Cambios realizados por Nival</h3>{data.changes.length?<ul className="ownerChangelog">{data.changes.map((c:Record<string,any>)=><li key={c.id}><time>{new Date(c.date).toLocaleDateString('es-MX',{timeZone:'America/Mexico_City'})}</time><p className="preserveLines">{c.description}</p></li>)}</ul>:<p className="ownerEmpty">No se registraron cambios en este periodo.</p>}</article></section>
 <section id="clientes" data-panel="clientes" className="ownerBlock"><div className="ownerSectionTitle"><small>RELACIONES QUE IMPORTAN</small><h2>Una comunidad que crece contigo</h2><p>Segmentos al {range.today}. Un cliente puede estar en más de uno. Solo se cuentan visitas; canjes y ajustes no agregan visitas.</p></div><CustomerExplorer customers={data.segments} demo={demo} businessId={b.id}/></section>

 {segments.map(([key,title,description,flag])=>{const customers=data.segments.filter((c:Record<string,any>)=>c[flag]);return <section key={key} id={'clientes-'+key} data-panel={'clientes-'+key} className="ownerBlock"><div className="ownerSectionTitle"><small>GRUPO DE CLIENTES</small><h2>{title}</h2><p>{description}. Segmentos al {range.today}; un cliente puede pertenecer a varios grupos.</p></div><CustomerExplorer key={key} customers={customers} demo={demo} businessId={b.id} fixedSegment={key}/><SegmentCard segment={key} title={'Acciones para clientes '+title.toLowerCase()} description={description} customers={customers} templates={data.templates as {segment:string;text:string}[]} businessName={b.name} demo={demo} messages={data.messages||[]}/></section>;})}

 <section data-panel="equipo" className="ownerBlock"><div className="workspaceSectionHeader"><div className="ownerSectionTitle"><small>PERSONAS QUE HACEN LA DIFERENCIA</small><h2>Tu equipo, en un solo lugar</h2><p>Consulta quién registra visitas y revisa los canjes pendientes.</p></div><a className="workspacePrimary" href={demo?'/acceso':'/panel/puntos?business='+b.id+'&view=equipo'}>Administrar personal <Icon name="arrow" size={16}/></a></div> <article className="ownerCard"><h3>Actividad de meseros</h3><p className="cardCaption">Señales para revisar; no prueban fraude. Volumen alto: al menos 10 visitas y más del doble del promedio de los demás operadores.</p>{!data.ranking.length?<p className="ownerEmpty">El ranking aparecerá con el primer movimiento.</p>:<ol className="staffRanking">{data.ranking.map((r:Record<string,any>)=>{const others=data.ranking.filter((x:Record<string,any>)=>x.staff_id!==r.staff_id),avg=others.length?others.reduce((s:number,x:Record<string,any>)=>s+x.visits,0)/others.length:0;const high=others.length>0&&r.visits>=10&&r.visits>avg*2;return <li key={r.staff_id}><b>{r.name}</b><span>{r.visits} visitas · {r.redemptions} canjes · {r.customers} clientes</span>{high&&<small className="ownerAlert">Revisar: volumen de visitas alto.</small>}{r.reversed>0&&<small className="ownerAlert">Revisar: {r.reversed} canjes revertidos.</small>}{r.pending>0&&<small>{r.pending} canjes pendientes de revisión.</small>}</li>;})}</ol>}</article><div className="workspaceInfoCard"><Icon name="check"/><div><h3>Cada integrante tiene su propio acceso</h3><p>Configura meseros con PIN y revisa su actividad desde tu programa de puntos. Los indicadores son señales para revisar, no pruebas de fraude.</p></div></div></section>
 <section data-panel="compartir" className="ownerBlock"><div className="ownerSectionTitle"><small>MENOS PASOS. MÁS PARTICIPACIÓN.</small><h2>Compartir QR y tarjeta</h2><p>{demo?'Esta muestra abre una tarjeta ficticia y no guarda datos. En un negocio activo, el QR permite a cada cliente crear su tarjeta. Después de una compra, el empleado escanea el QR personal del cliente para sumar puntos.':'Este QR permite que tus clientes creen su tarjeta. Para sumar puntos, tu empleado escanea el QR personal que aparece en la tarjeta de cada cliente.'}</p></div><ShareTools slug={b.slug} name={b.name} demo={demo}/></section>
 {demo&&<section data-panel="programa" className="ownerBlock"><h2>Programa de puntos</h2><p>En tu cuenta configura la tarjeta, reglas de visitas y premios desde esta sección.</p></section>}
 <section data-panel="ajustes" className="ownerBlock"><div className="ownerSectionTitle"><small>CUENTA DEL NEGOCIO</small><h2>Datos y plan</h2>{!demo&&<a href={"/panel/reportes?business="+b.id}>Mis reportes PDF y recomendaciones</a>}<p>Consulta los datos, el servicio y el plan de tu negocio. La tarjeta y los premios se configuran en Puntos.</p></div><div className="settingsOverview"><article className="ownerCard"><span className="workspaceEyebrow">TU NEGOCIO</span><h3>{b.name}</h3><dl><div><dt>Responsable</dt><dd>{b.owner_name||actor.name}</dd></div><div><dt>Giro</dt><dd>{b.giro||'Sin registrar'}</dd></div><div><dt>Servicio</dt><dd>{status}</dd></div><div><dt>Plan</dt><dd>{b.plan_name||'Por confirmar con Nival'}</dd><dt>Vencimiento</dt><dd>{b.paid_until?new Date(b.paid_until).toLocaleDateString('es-MX',{timeZone:'America/Mexico_City'}):'Comienza al activar el código'}</dd></div></dl>{!demo&&<a className="workspaceSecondary" href={quote} target="_blank" rel="noreferrer">Hablar con Nival</a>}</article></div>
 {!demo&&<PlanChoices b={b}/>}
 {!demo&&businesses.length>1&&<article className="ownerCard"><h3>Cambiar de negocio</h3><div className="workspaceActionRow">{businesses.map((x:Record<string,any>)=><a className="workspaceSecondary" key={x.id} href={'/panel?business='+x.id+'#ajustes'} aria-current={x.id===b.id?'page':undefined}>{x.name}</a>)}</div></article>}
  {!demo&&<details className="ownerCard"><summary>Configurar umbrales de clientes</summary><ActionForm action={saveSegments} label="Guardar umbrales"><Hidden name="businessId" value={b.id}/>{[['new_days','Días para nuevos',365],['frequent_days','Ventana de frecuentes (días)',365],['frequent_visits','Visitas mínimas para frecuentes',100],['risk_from','Días sin venir: inicio de riesgo',730],['lost_after','Días sin venir: fin de riesgo',731],['risk_visits','Visitas mínimas previas para riesgo',100]].map(([name,label,max])=><Field key={name} name={String(name)} label={String(label)} type="number" min={name==='lost_after'?2:1} max={Number(max)} value={settings[String(name)]}/>)}</ActionForm></details>} {!demo&&<details className="ownerCard"><summary>Plantillas de WhatsApp</summary><p>Variables disponibles: {'{nombre}'}, {'{puntos}'}, {'{premio}'} y {'{negocio}'}. El envío es individual y requiere autorización del cliente.</p>{Object.entries(defaultMessages).map(([key,body])=><ActionForm key={key} action={saveMessageTemplate} label="Guardar plantilla"><Hidden name="businessId" value={b.id}/><Hidden name="segment" value={key}/><label>Mensaje: {({new:'Nuevo',active:'Activo',frequent:'Frecuente',risk:'En riesgo',lost:'Inactivo',near_reward:'Cerca del premio'} as Record<string,string>)[key]}<textarea name="body" required maxLength={1500} defaultValue={data.messages?.find((t:Record<string,any>)=>t.segment===key)?.body||body}/></label></ActionForm>)}</details>} {!demo&&<details className="ownerCard"><summary>Registrar otro negocio</summary><ActionForm action={registerBusiness} label="Registrar negocio" preserveOnError><RegistrationFields/></ActionForm></details>}{demo&&<div className="workspaceInfoCard"><Icon name="ajustes"/><div><h3>En tu cuenta puedes personalizar el programa</h3><p>La demo permite recorrer el panel. Los cambios de configuración se realizan dentro del negocio registrado.</p></div></div>}</section>
 </main></DashboardShell>;
}
