import {DashboardShell} from './shell';
import {CustomerExplorer} from './customer-explorer';
import {ShareTools} from './share-tools';
import {Icon} from './icons';
import {quoteUrl} from "../foundation/registration.mjs";
import {RegistrationFields} from "../foundation/registration-fields";
import {logout,registerBusiness} from '../foundation/actions';
import {redeemActivationCode} from '../admin/actions';
import {ActionForm} from '../foundation/forms';
import {Field,Hidden} from '../foundation/fields';
import {checklistLabels,periodRange} from './domain.mjs';
import {Bars,RatingLine} from './charts';
import {SegmentCard,PeriodFilter} from './clients';
import {saveSegments} from './actions';
const number=(v:number)=>Number(v||0).toLocaleString('es-MX');
function Metric({label,value,previous}:{label:string;value:number|string;previous?:number}){return <article className="ownerCard ownerMetric"><span>{label}</span><strong>{typeof value==='number'?number(value):value}</strong>{previous!==undefined&&<small>{Number(value)-previous>0?'+':''}{number(Number(value)-previous)} respecto al anterior · {number(previous)} antes</small>}</article>;}
export function OwnerView({actor,b,businesses,range,data,demo=false}:{actor:Record<string,any>;b:Record<string,any>;businesses:Record<string,any>[];range:ReturnType<typeof periodRange>;data:Record<string,any>;demo?:boolean}){
 const current=data.metrics.find((x:Record<string,any>)=>x.period==='current')!,prev=data.metrics.find((x:Record<string,any>)=>x.period==='previous')!;
 const settings=data.settings||{new_days:14,frequent_days:30,frequent_visits:3,risk_from:31,lost_after:60,risk_visits:2};
 const segments=[['new','Nuevos',`Primera visita en los últimos ${settings.new_days} días`,'is_new'],['frequent','Frecuentes',`${settings.frequent_visits}+ visitas en los últimos ${settings.frequent_days} días`,'is_frequent'],['risk','En riesgo',`${settings.risk_from}–${settings.lost_after} días sin venir y ${settings.risk_visits}+ visitas`,'is_risk'],['lost','Perdidos',`Más de ${settings.lost_after} días sin visitar`,'is_lost'],['absent','No han venido este mes','Incluye tarjetas que aún no tienen una visita','absent_month']];
 const last=data.last,distribution=last?.distribution||{},hasDistribution=[1,2,3,4,5].reduce((s,n)=>s+Number(distribution[n]||0),0)===Number(last?.total_reviews)&&Object.keys(distribution).length>0;
 const quote=quoteUrl(b);
 const active=b.status==='activo'&&(new Date(b.paid_until||0).getTime()>Date.now()||new Date(b.trial_ends_at||0).getTime()>Date.now());
 const risk=data.segments.filter((c:Record<string,any>)=>c.is_risk||c.is_lost).length;
 const returners=data.segments.filter((c:Record<string,any>)=>c.is_frequent).length;
 const status=active||demo?'Activo':b.status==='pausado'?'Pausado':'Por activar';
 return <DashboardShell name={b.name} owner={actor.name} status={status} demo={demo} logout={<form action={logout}><button className="logoutButton" aria-label="Cerrar sesión" title="Cerrar sesión"><Icon name="logout" size={18}/></button></form>}><main className="ownerDashboard">
 {!demo&&!active&&<section className="ownerCard accountLock"><div><span className="workspaceEyebrow">ESTADO DE TU SERVICIO</span><h2>Tu negocio está listo. Activa tu programa.</h2><p>Consulta tu información y contacta a Nival para empezar a registrar visitas.</p></div><a className="workspacePrimary" href={quote} target="_blank" rel="noreferrer">Cotizar o activar por WhatsApp <Icon name="arrow" size={16}/></a><ActionForm action={redeemActivationCode} label="Activar con código"><Hidden name="businessId" value={b.id}/><Field name="code" label="Código NIV-XXXX-XXXX"/></ActionForm></section>}
 <div className="workspacePeriod"><div><Icon name="clock" size={18}/><span>Periodo de tus resultados</span></div>
 <PeriodFilter demo={demo} businessId={b.id} kind={range.kind} value={range.key}/></div><p className="periodCaption">Del {range.start} al {range.end} (fin excluido) · Hora de Ciudad de México · Comparado con el periodo anterior.</p>
 <section id="resumen" data-panel="inicio" className="ownerBlock"><div className="workspaceHero"><div><span className="heroKicker"><span/> TU NEGOCIO, CONECTADO</span><h2>Cada cliente que vuelve<br/>hace crecer tu negocio.</h2><p>Hola, {actor.name.split(' ')[0]}. Este es el pulso de {b.name} en el periodo seleccionado.</p><div className="workspaceActionRow"><a href="#clientes" className="workspacePrimary">Ver mis clientes <Icon name="arrow" size={16}/></a><a href="#compartir" className="heroTextLink">Compartir mi tarjeta <Icon name="compartir" size={16}/></a></div></div><div className="heroSignal"><Icon name="clientes" size={28}/><strong>{number(data.segments.length)}</strong><span>clientes en tu comunidad</span><div><span/> {number(returners)} clientes frecuentes</div></div></div><div className="ownerSectionTitle"><small>EL PULSO DE TU NEGOCIO</small><h2>Resumen</h2></div><div className="ownerMetrics">
 {([['Visitas','visits'],['Clientes nuevos','new_customers'],['Puntos otorgados','points'],['Premios canjeados','redeemed'],['Canjes pendientes del periodo','pending']] as const).map(([label,key])=><Metric key={key} label={label} value={current[key]} previous={prev[key]}/>)}</div>
 {!current.visits&&<p className="ownerEmpty">Aún no hay visitas en este periodo. Comparte el QR del negocio y registra cada visita desde el escáner del mesero.</p>}
 <div className="overviewBottom"><article className="ownerCard overviewComparison"><div className="workspaceCardHead"><div><span className="workspaceEyebrow">EVOLUCIÓN DEL NEGOCIO</span><h3>Visitas del periodo</h3></div><Icon name="trend"/></div><div className="comparisonHeadline"><strong>{number(current.visits)}</strong><span>{prev.visits>0?`${Math.round((current.visits-prev.visits)/prev.visits*100)>0?'+':''}${Math.round((current.visits-prev.visits)/prev.visits*100)}% vs. periodo anterior`:'Sin base anterior para comparar'}</span></div><Bars title="Comparación de visitas" unit="Visitas registradas en cada periodo" items={[{label:'Este periodo',value:Number(current.visits),color:'#226e57'},{label:'Anterior',value:Number(prev.visits),color:'#c4d5cc'}]}/></article><article className="ownerCard nextActions"><span className="workspaceEyebrow">TU SIGUIENTE PASO</span><h3>Pequeñas acciones. Más regresos.</h3><a href="#clientes"><span className="actionIcon"><Icon name="clientes"/></span><span><strong>{risk?`${risk} clientes por recuperar`:'Construye una relación con tus clientes'}</strong><small>Revisa los segmentos y prepara un mensaje personal.</small></span><Icon name="arrow" size={16}/></a><a href="#google"><span className="actionIcon"><Icon name="google"/></span><span><strong>{data.google?.answered!==null&&data.google?`${Math.max(0,data.google.fresh-data.google.answered)} reseñas pendientes del periodo`:'Consulta tu reputación en Google'}</strong><small>Revisa tus reportes y el trabajo realizado por Nival.</small></span><Icon name="arrow" size={16}/></a><a href="#compartir"><span className="actionIcon"><Icon name="compartir"/></span><span><strong>Haz visible tu programa de puntos</strong><small>Descarga el QR para tu mostrador.</small></span><Icon name="arrow" size={16}/></a></article></div></section>
 <section id="google" data-panel="google" className="ownerBlock"><div className="ownerSectionTitle"><small>DATOS CARGADOS POR NIVAL</small><h2>Tu reputación, en perspectiva</h2></div>
 {last?<><p className="cardCaption">Ficha al cierre del último reporte disponible: {String(last.period).slice(0,10)} · {last.period_kind==='day'?'diario':last.period_kind==='year'?'anual':'mensual'}.</p><div className="ownerMetrics"><Metric label="Calificación al cierre" value={String(last.rating)+' ★'}/><Metric label="Reseñas totales" value={Number(last.total_reviews)}/><Metric label="Nuevas del periodo" value={data.google?data.google.fresh:'—'}/><Metric label="Respondidas del periodo" value={data.google?.answered!==null&&data.google?data.google.answered:'—'}/><Metric label="Pendientes del periodo" value={data.google?.answered!==null&&data.google?Math.max(0,data.google.fresh-data.google.answered):'—'}/><Metric label="Respuesta del periodo" value={data.google?.answered!==null&&data.google?(data.google.fresh?Math.round(data.google.answered/data.google.fresh*100)+'%':'—'):'—'}/></div>
 {data.google&&data.google.answered===null&&<p className="ownerEmpty">Este reporte histórico no separa respuestas del periodo. Nival debe actualizarlo desde admin para mostrar pendientes y porcentaje.</p>}
 {!data.google&&<p className="ownerEmpty">No hay reporte para este filtro. Un reporte mensual no se divide en cifras diarias: elige el mes o espera la carga del día.</p>}
 {data.google&&<p className="cardCaption">Cifras de nuevas y respuestas basadas en reportes {data.google.resolution==='day'?'diarios':data.google.resolution==='year'?'anuales':'mensuales'}. La ficha y su distribución son una fotografía al cierre, no una suma de totales.</p>}
 <div className="ownerChartGrid">{hasDistribution?<><Bars title="Distribución por estrellas" items={[5,4,3,2,1].map(n=>({label:n+' ★',value:Number(distribution[n]||0),color:'#175d47'}))}/><Bars title="Sentimiento de las reseñas" items={[{label:'Positivas · 4–5',value:Number(distribution[4]||0)+Number(distribution[5]||0),color:'#175d47'},{label:'Neutras · 3',value:Number(distribution[3]||0),color:'#b98832'},{label:'Negativas · 1–2',value:Number(distribution[1]||0)+Number(distribution[2]||0),color:'#ba5850'}]}/></>:<p className="ownerEmpty">Nival todavía debe cargar una distribución por estrellas que coincida con el total.</p>}<RatingLine reports={data.reports}/></div>
 <div className="ownerChartGrid"><article className="ownerCard"><h3>Áreas de mejora de la ficha</h3><ul className="profileChecklist">{Object.entries(checklistLabels).map(([k,label])=><li key={k}><span>{label}</span><b className={last.profile_checklist[k]?'checkDone':'checkPending'}>{last.profile_checklist[k]?'✓ Revisado':'Pendiente'}</b></li>)}</ul></article><article className="ownerCard"><h3>Consejos de Nival</h3><p className="preserveLines">{last.notes||'Nival aún no ha agregado consejos a este reporte.'}</p></article></div></>:<p className="ownerEmpty">Tu primer reporte está pendiente. Comparte con Nival el enlace de tu ficha de Google para iniciar la revisión; aquí verás las métricas cuando se carguen.</p>}
 <article className="ownerCard"><h3>Cambios realizados por Nival</h3>{data.changes.length?<ul className="ownerChangelog">{data.changes.map((c:Record<string,any>)=><li key={c.id}><time>{new Date(c.date).toLocaleDateString('es-MX',{timeZone:'America/Mexico_City'})}</time><p className="preserveLines">{c.description}</p></li>)}</ul>:<p className="ownerEmpty">No se registraron cambios en este periodo.</p>}</article></section>
 <section id="clientes" data-panel="clientes" className="ownerBlock"><div className="ownerSectionTitle"><small>RELACIONES QUE IMPORTAN</small><h2>Una comunidad que crece contigo</h2><p>Segmentos al {range.today}. Un cliente puede estar en más de uno. Solo se cuentan visitas; canjes y ajustes no agregan visitas.</p></div><CustomerExplorer customers={data.segments} demo={demo}/><div className="workspaceSectionSubhead"><h3>Encuentra tu próxima oportunidad</h3><p>Segmentos de clientes y consejos para impulsar su próxima visita.</p></div><div className="ownerSegmentGrid">{segments.map(([key,title,description,flag])=><SegmentCard key={key} segment={key} title={title} description={description} customers={data.segments.filter((c:Record<string,any>)=>c[flag])} templates={data.templates as {segment:string;text:string}[]} businessName={b.name} demo={demo}/>)}</div>
</section>

 <section data-panel="equipo" className="ownerBlock"><div className="workspaceSectionHeader"><div className="ownerSectionTitle"><small>PERSONAS QUE HACEN LA DIFERENCIA</small><h2>Tu equipo, en un solo lugar</h2><p>Consulta quién registra visitas y revisa los canjes pendientes.</p></div><a className="workspacePrimary" href={demo?'/acceso':'/panel/puntos?business='+b.id}>Administrar personal <Icon name="arrow" size={16}/></a></div> <article className="ownerCard"><h3>Actividad de meseros</h3><p className="cardCaption">Señales para revisar; no prueban fraude. Volumen alto: al menos 10 visitas y más del doble del promedio de los demás operadores.</p>{!data.ranking.length?<p className="ownerEmpty">El ranking aparecerá con el primer movimiento.</p>:<ol className="staffRanking">{data.ranking.map((r:Record<string,any>)=>{const others=data.ranking.filter((x:Record<string,any>)=>x.staff_id!==r.staff_id),avg=others.length?others.reduce((s:number,x:Record<string,any>)=>s+x.visits,0)/others.length:0;const high=others.length>0&&r.visits>=10&&r.visits>avg*2;return <li key={r.staff_id}><b>{r.name}</b><span>{r.visits} visitas · {r.redemptions} canjes · {r.customers} clientes</span>{high&&<small className="ownerAlert">Revisar: volumen de visitas alto.</small>}{r.reversed>0&&<small className="ownerAlert">Revisar: {r.reversed} canjes revertidos.</small>}{r.pending>0&&<small>{r.pending} canjes pendientes de revisión.</small>}</li>;})}</ol>}</article><div className="workspaceInfoCard"><Icon name="check"/><div><h3>Cada integrante tiene su propio acceso</h3><p>Configura meseros con PIN y revisa su actividad desde tu programa de puntos. Los indicadores son señales para revisar, no pruebas de fraude.</p></div></div></section>
 <section data-panel="compartir" className="ownerBlock"><div className="ownerSectionTitle"><small>MENOS PASOS. MÁS PARTICIPACIÓN.</small><h2>La puerta de entrada a tu programa</h2><p>Un QR y un enlace para que tus clientes lleven su tarjeta en el celular.</p></div><ShareTools slug={b.slug} name={b.name} demo={demo}/></section>
 <section data-panel="ajustes" className="ownerBlock"><div className="ownerSectionTitle"><small>HECHO A LA MEDIDA DE TU NEGOCIO</small><h2>Todo en su lugar</h2><p>Personaliza tu programa y administra los datos de tu negocio.</p></div><div className="settingsOverview"><article className="ownerCard"><span className="workspaceEyebrow">TU NEGOCIO</span><h3>{b.name}</h3><dl><div><dt>Responsable</dt><dd>{b.owner_name||actor.name}</dd></div><div><dt>Giro</dt><dd>{b.giro||'Sin registrar'}</dd></div><div><dt>Servicio</dt><dd>{status}</dd></div><div><dt>Plan</dt><dd>{b.plan_name||'Por confirmar con Nival'}</dd></div></dl>{!demo&&<a className="workspaceSecondary" href={quote} target="_blank" rel="noreferrer">Hablar con Nival</a>}</article><article className="ownerCard"><span className="workspaceEyebrow">TU PROGRAMA DE LEALTAD</span><h3>Una experiencia con tu identidad</h3><p>Configura tus premios, puntos por visita, colores, logo y accesos del equipo.</p><a className="workspacePrimary" href={demo?'/acceso':'/panel/puntos?business='+b.id}>Configurar mi programa <Icon name="arrow" size={16}/></a></article></div>
 {!demo&&businesses.length>1&&<article className="ownerCard"><h3>Cambiar de negocio</h3><div className="workspaceActionRow">{businesses.map((x:Record<string,any>)=><a className="workspaceSecondary" key={x.id} href={'/panel?business='+x.id+'#ajustes'} aria-current={x.id===b.id?'page':undefined}>{x.name}</a>)}</div></article>}
  {!demo&&<details className="ownerCard"><summary>Configurar umbrales de clientes</summary><ActionForm action={saveSegments} label="Guardar umbrales"><Hidden name="businessId" value={b.id}/>{[['new_days','Días para nuevos',365],['frequent_days','Ventana de frecuentes (días)',365],['frequent_visits','Visitas mínimas para frecuentes',100],['risk_from','Días sin venir: inicio de riesgo',730],['lost_after','Días sin venir: fin de riesgo',731],['risk_visits','Visitas mínimas previas para riesgo',100]].map(([name,label,max])=><Field key={name} name={String(name)} label={String(label)} type="number" min={name==='lost_after'?2:1} max={Number(max)} value={settings[String(name)]}/>)}</ActionForm></details>} {!demo&&<details className="ownerCard"><summary>Registrar otro negocio</summary><ActionForm action={registerBusiness} label="Registrar negocio" preserveOnError><RegistrationFields/></ActionForm></details>}{demo&&<div className="workspaceInfoCard"><Icon name="ajustes"/><div><h3>En tu cuenta puedes personalizar el programa</h3><p>La demo permite recorrer el panel. Los cambios de configuración se realizan dentro del negocio registrado.</p></div></div>}</section>
 </main></DashboardShell>;
}
