'use client';
import {useEffect,useState} from 'react';
import {useLocalData} from '../../lib/use-local-data';
import {monthInMexico} from '../../lib/mexico-date';
import {customersValid,movementsValid,reviewsValid} from '../../lib/validators';
import {loyaltyMetrics,reviewMetrics,type Customer,type Movement,type Review} from '../../lib/metrics';
import DemoNotice from '../components/demo-notice';
const emptyCustomers:Customer[]=[];const emptyMovements:Movement[]=[];const emptyReviews:Review[]=[];
export default function Business(){
 const customers=useLocalData('nival-clientes',emptyCustomers,customersValid);const movements=useLocalData('nival-movements-v1',emptyMovements,movementsValid);const reviews=useLocalData('nival-reviews-v1',emptyReviews,reviewsValid);
 const[account,setAccount]=useState<{nombre:string;negocio:string}|null>(null);const[month,setMonth]=useState('');const[error,setError]=useState('');const[riskDays,setRiskDays]=useState(30);
 useEffect(()=>{setMonth(monthInMexico());try{const raw=localStorage.getItem('nival-cuenta');if(raw){const c=JSON.parse(raw);if(typeof c.nombre==='string'&&typeof c.negocio==='string')setAccount(c);else throw Error('invalid');}const config=JSON.parse(localStorage.getItem('nival-config')||'{}');if(Number.isInteger(config.riskDays)&&config.riskDays>0)setRiskDays(config.riskDays);}catch{setError('No se pudo leer el perfil o la configuración guardada.');}},[]);
 const r=reviewMetrics(reviews.data,month);const p=loyaltyMetrics(customers.data,movements.data,month,riskDays);
 function download(){if(!account||!month)return;const report={negocio:account.negocio,mes:month,resenas:r,puntos:{clientesNuevos:p.newCustomers,clientesRegresaron:p.returning,clientesEnRiesgo:p.risk.length,visitas:p.visits,puntosOtorgados:p.points},nota:'Resumen de datos capturados manualmente. No es una lectura automática de Google.'};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`nival-resumen-${month}.json`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(!customers.ready||!movements.ready||!reviews.ready)return <main className="dashboard">Cargando resumen…</main>;
 return <main className="dashboard"><DemoNotice/><header className="dashHead"><div><small>NIVAL · MI NEGOCIO</small><h1>{account?.negocio||'Tu negocio'}</h1><p>{account?`Hola, ${account.nombre}`:'Registra tu perfil de prueba para comenzar.'}</p></div><a href="/registro">Perfil</a></header>{[error,customers.error,movements.error,reviews.error].filter(Boolean).map((e,i)=><p key={i} role="alert" className="error">{e}</p>)}{!account&&<section className="reviewBox"><h2>Configura tu negocio</h2><a href="/registro" className="primary">Crear perfil de prueba</a></section>}<label className="filter">Mes del resumen<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><section className="stats"><article><span>Reseñas nuevas</span><b>{r.total}</b></article><article><span>Respondidas</span><b>{r.answered}</b></article><article><span>Visitas registradas</span><b>{p.visits}</b></article></section><section className="reviewBox"><h2>Resumen mensual</h2><p>En {month||'este mes'} se capturaron {r.total} reseñas: {r.positive} positivas, {r.neutral} neutrales y {r.negative} negativas. De esas reseñas, {r.answered} tienen respuesta confirmada y {r.total-r.answered} están pendientes.</p><p>El programa de puntos registró {p.newCustomers} clientes nuevos, {p.returning} clientes que regresaron y {p.visits} visitas. Se otorgaron {p.points} puntos. Actualmente hay {p.risk.length} clientes sin regresar por más de {riskDays} días.</p><p>Estas cifras se calculan con la información capturada. La calificación global de Google no se deduce de una muestra de reseñas.</p><button disabled={!!error||!!customers.error||!!movements.error||!!reviews.error||!month||!account} onClick={download}>Descargar resumen</button></section><section className="reviewBox"><h2>Nival Puntos</h2><p>Registra visitas, consulta clientes y canjea recompensas.</p><a className="primary" href="/puntos">Administrar puntos</a></section><section className="reviewBox"><h2>Seguimiento de reseñas</h2><p>Los resultados aparecerán después de capturarlos en el módulo de seguimiento.</p><a href="/nival">Ver captura manual de prueba</a></section><p className="notice">Los reportes anteriores permanecen guardados. El resumen nuevo usa el historial de visitas y reseñas.</p></main>;
}
