'use server';
import {validDate} from '../../../lib/diagnostics';
import {mexicoDate} from '../../../lib/monthly-report';
import {createClient} from '../../../lib/supabase/server';
import {revalidatePath} from 'next/cache';
import type {ActionResult} from '../actions';
async function operator(){const client=await createClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw Error('auth');const{data:role,error:roleError}=await client.from('npr_operators').select('user_id').eq('user_id',data.user.id).maybeSingle();if(roleError||!role)throw Error('role');return client;}
export async function captureReview(_:ActionResult,form:FormData):Promise<ActionResult>{const id=String(form.get('business')||'');const author=String(form.get('author')||'').trim();const body=String(form.get('body')||'').trim();const rating=Number(form.get('rating'));const date=String(form.get('date')||'');if(!/^[0-9a-f-]{36}$/i.test(id)||!author||author.length>100||body.length>5000||!Number.isInteger(rating)||rating<1||rating>5||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||date>new Date().toISOString().slice(0,10))return {error:'Revisa el negocio, el nombre, la fecha y la calificación.'};try{const client=await operator();const{error}=await client.from('npr_reviews').insert({business_id:id,author,body,rating,review_date:date});if(error)return {error:'No se pudo guardar la reseña. Revisa los datos.'};revalidatePath('/panel');revalidatePath('/panel/nival');return {success:'Reseña cargada para el negocio.'};}catch{return {error:'Solo el operador de Nival puede capturar reseñas.'};}}
export async function confirmResponse(_:ActionResult,form:FormData):Promise<ActionResult>{const id=String(form.get('review')||'');if(form.get('published')!=='yes')return {error:'Confirma primero que publicaste la respuesta en Google.'};try{const client=await operator();const{data,error}=await client.from('npr_reviews').update({answered_at:new Date().toISOString()}).eq('id',id).is('answered_at',null).select('id');if(error||!data?.length)return {error:'No se pudo actualizar; puede que ya estuviera respondida.'};revalidatePath('/panel');revalidatePath('/panel/nival');return {success:'Respuesta confirmada.'};}catch{return {error:'Necesitas el acceso interno de Nival.'};}}

export async function captureDiagnostic(_:ActionResult,form:FormData):Promise<ActionResult>{
 const business=String(form.get('business')||'');const date=String(form.get('date')||'');const rating=Number(form.get('rating'));const count=Number(form.get('count'));const findings=String(form.get('findings')||'').trim();const recommendations=String(form.get('recommendations')||'').trim();
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(business)||!validDate(date,mexicoDate())||!Number.isFinite(rating)||rating<1||rating>5||Math.abs(rating*10-Math.round(rating*10))>0.00001||!Number.isInteger(count)||count<0||count>2147483647||!findings||findings.length>5000||!recommendations||recommendations.length>5000)return {error:'Revisa la fecha, calificación, total de reseñas y notas del diagnóstico.'};
 try{const client=await operator();const{error}=await client.from('npr_diagnostics').insert({business_id:business,checked_on:date,rating,review_count:count,findings,recommendations});if(error)return {error:error.code==='23505'?'Ya existe un diagnóstico de ese negocio en esta fecha.':'No se pudo guardar el diagnóstico. Comprueba la configuración de la base independiente.'};revalidatePath('/panel/reporte');revalidatePath('/panel/nival');return {success:'Diagnóstico guardado para el negocio.'};}catch{return {error:'Necesitas el acceso interno de Nival.'};}
}
