'use client';
import {useActionState} from 'react';
import {captureReview,confirmResponse,captureDiagnostic} from './actions';
import type {ActionResult} from '../actions';
const initial:ActionResult={};
export function CaptureForm({businesses}:{businesses:{id:string;name:string}[]}){const[state,action,pending]=useActionState(captureReview,initial);return <form action={action} className="configGrid"><label>Negocio<select required name="business">{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Autor en Google<input name="author" required maxLength={100}/></label><label>Calificación<select name="rating">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} estrellas</option>)}</select></label><label>Fecha<input type="date" name="date" required/></label><label className="wide">Texto<textarea name="body" maxLength={5000}/></label><button disabled={pending||businesses.length===0}>Guardar reseña</button><p role="status">{state.error||state.success}</p></form>}
export function ResponseForm({id}:{id:string}){const[state,action,pending]=useActionState(confirmResponse,initial);return <form action={action}><input type="hidden" name="review" value={id}/><label><input type="checkbox" name="published" value="yes" required/> Ya publiqué la respuesta en Google</label><button disabled={pending}>Confirmar respuesta</button><p role="status">{state.error||state.success}</p></form>}

export function DiagnosticForm({businesses}:{businesses:{id:string;name:string}[]}){const[state,action,pending]=useActionState(captureDiagnostic,initial);return <form action={action} className="configGrid"><label>Negocio<select required name="business">{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Fecha de revisión<input type="date" name="date" required/></label><label>Calificación general de Google<input type="number" name="rating" min="1" max="5" step="0.1" required/></label><label>Total de reseñas en Google<input type="number" name="count" min="0" max="2147483647" step="1" required/></label><label className="wide">Hallazgos de la ficha<textarea name="findings" required maxLength={5000}/></label><label className="wide">Recomendaciones para el negocio<textarea name="recommendations" required maxLength={5000}/></label><button disabled={pending||!businesses.length}>Guardar diagnóstico</button><p role="status">{state.error||state.success}</p></form>}
